from __future__ import annotations

import csv
import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "generate_rule_compatibility_projections.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("test_rule_projection_generator", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _fixture(root: Path, *, missing_canonical: bool = False, count: int = 38) -> Path:
    policy = root / "policy.toml"
    csv_path = root / "moves.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "Current home directory:",
                "Current file name:",
                "New home directory:",
                "New file name:",
            ]
        )
        for index in range(count):
            writer.writerow(
                [
                    f"{root}/.claude/rules",
                    f"rule-{index}.md",
                    f"{root}/config/agent-control",
                    f"gtkb-rule-{index}.md",
                ]
            )
    lines = [
        "schema_version = 1",
        'manifest_path = "moves.csv"',
        "",
        "[retention]",
        f"native_rule_projection_count = {count}",
        "",
    ]
    for index in range(count):
        canonical = root / "config" / "agent-control" / f"gtkb-rule-{index}.md"
        if not missing_canonical or index != 0:
            canonical.parent.mkdir(parents=True, exist_ok=True)
            canonical.write_bytes(f"rule {index}\r\n".encode())
        lines.extend(
            [
                "[[rule_projections]]",
                f'source = ".claude/rules/rule-{index}.md"',
                f'canonical = "config/agent-control/gtkb-rule-{index}.md"',
                'class = "projection"',
                'load_policy = "explicit_query"',
                "",
            ]
        )
    policy.write_text("\n".join(lines), encoding="utf-8")
    return policy


def test_live_policy_count_field_and_retired_writer() -> None:
    module = _load_module()
    policy = module.load_policy(ROOT)
    assert module.native_rule_projection_count(policy) >= 1
    with pytest.raises(module.RuleProjectionError, match="project_harness.py"):
        module.generate(ROOT)


def test_policy_count_is_single_authority(tmp_path: Path) -> None:
    module = _load_module()
    policy_path = _fixture(tmp_path, count=3)
    policy = module.load_policy(tmp_path, policy_path)
    rows = module.projection_rows(policy)
    assert len(rows) == module.native_rule_projection_count(policy) == 3


def test_generate_write_is_retired(tmp_path: Path) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, count=2)
    with pytest.raises(module.RuleProjectionError, match="project_harness.py"):
        module.generate(tmp_path, policy_path=policy)
    assert not (tmp_path / ".claude/rules/rule-0.md").exists()
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(tmp_path),
            "--policy",
            str(policy),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 2
    assert "project_harness.py" in completed.stderr


def test_check_reports_drift_without_writing(tmp_path: Path) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, count=2)
    target = tmp_path / ".claude/rules/rule-0.md"
    target.parent.mkdir(parents=True)
    target.write_bytes(b"manual\n")
    results = module.generate(tmp_path, policy_path=policy, check=True)
    assert next(item for item in results if item.source.endswith("rule-0.md")).changed
    assert target.read_bytes() == b"manual\n"


def test_check_cli_reports_drift_as_informational(tmp_path: Path) -> None:
    policy = _fixture(tmp_path, count=1)
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(tmp_path),
            "--policy",
            str(policy),
            "--check",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0
    assert (
        "content drift detected: 1 file(s) would be regenerated by scripts/harness_projection/project_harness.py"
    ) in completed.stdout
    assert "PROJECT-GTKB-OBSOLETE-REFERENCE-PURGE / WI-6448 / WI-6386" in completed.stdout
    assert "this informational mode retires when those land" in completed.stdout
    assert not (tmp_path / ".claude/rules/rule-0.md").exists()


def test_check_cli_reports_current_without_drift_marker(tmp_path: Path) -> None:
    policy = _fixture(tmp_path, count=1)
    target = tmp_path / ".claude/rules/rule-0.md"
    target.parent.mkdir(parents=True)
    target.write_bytes(b"rule 0\n")
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(tmp_path),
            "--policy",
            str(policy),
            "--check",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0
    assert "Rule compatibility projections: PASS (1 projections current)" in completed.stdout
    assert "content drift detected" not in completed.stdout


def test_line_ending_only_difference_is_not_drift(tmp_path: Path) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, count=1)
    target = tmp_path / ".claude/rules/rule-0.md"
    target.parent.mkdir(parents=True)
    target.write_bytes(b"rule 0\n")
    results = module.generate(tmp_path, policy_path=policy, check=True)
    assert not results[0].changed


def test_content_difference_is_drift(tmp_path: Path) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, count=1)
    target = tmp_path / ".claude/rules/rule-0.md"
    target.parent.mkdir(parents=True)
    target.write_bytes(b"rule changed\n")
    results = module.generate(tmp_path, policy_path=policy, check=True)
    assert results[0].changed


def test_render_outputs_is_side_effect_free_and_uses_canonical_override(
    tmp_path: Path,
) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, count=1)
    canonical = "config/agent-control/gtkb-rule-0.md"
    projection = tmp_path / ".claude/rules/rule-0.md"
    before = sorted(path.relative_to(tmp_path).as_posix() for path in tmp_path.rglob("*"))
    _rows, outputs = module.render_outputs(
        tmp_path,
        policy_path=policy,
        canonical_overrides={canonical: b"planned replacement\n"},
    )
    after = sorted(path.relative_to(tmp_path).as_posix() for path in tmp_path.rglob("*"))
    assert outputs[".claude/rules/rule-0.md"] == b"planned replacement\n"
    assert not projection.exists()
    assert before == after


def test_missing_canonical_fails_without_deleting_projection(tmp_path: Path) -> None:
    module = _load_module()
    policy = _fixture(tmp_path, missing_canonical=True, count=2)
    target = tmp_path / ".claude/rules/rule-0.md"
    target.parent.mkdir(parents=True)
    target.write_bytes(b"retained\n")
    with pytest.raises(module.RuleProjectionError, match="Canonical rule is missing"):
        module.generate(tmp_path, policy_path=policy, check=True)
    assert target.read_bytes() == b"retained\n"


def test_explicit_link_rewrite_skips_code_and_preserves_fragment() -> None:
    module = _load_module()
    rewrite = module.LinkRewrite(
        "config/agent-control/gtkb-a.md",
        "gtkb-b.md",
        "config/agent-control/gtkb-b.md",
        1,
    )
    text = "[live](gtkb-b.md#x) ` [inline](gtkb-b.md)`\n```md\n[code](gtkb-b.md)\n```\n"
    rendered = module.stabilize_relative_links(text, "config/agent-control/gtkb-a.md", [rewrite])
    assert "[live](config/agent-control/gtkb-b.md#x)" in rendered
    assert "` [inline](gtkb-b.md)`" in rendered
    assert "[code](gtkb-b.md)" in rendered


def test_unresolved_token_fails_before_write(tmp_path: Path) -> None:
    sys.path.insert(0, str(ROOT / "scripts" / "harness_projection"))
    import project_harness

    plan = project_harness.Plan()
    result = project_harness.substitute(
        "path is {{HARNESS_UNKNOWN_TOKEN}}",
        {"HARNESS_NAME": "x"},
        str(tmp_path / "f.md"),
        plan.gaps,
    )
    assert "{{HARNESS_UNKNOWN_TOKEN}}" in result
    assert plan.gaps and "unresolved token" in plan.gaps[0]
    assert not any(tmp_path.rglob("*"))
