from __future__ import annotations

import hashlib
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "check_harness_parity.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("check_harness_parity", SCRIPT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["check_harness_parity"] = module
    spec.loader.exec_module(module)
    return module


def _write_skill(project_root: Path, directory: str, name: str | None = None) -> None:
    skill_dir = project_root / ".claude" / "skills" / directory
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_name = name or directory
    skill_dir.joinpath("SKILL.md").write_text(
        f"---\nname: {skill_name}\ndescription: Test skill.\n---\n\n# {skill_name}\n",
        encoding="utf-8",
    )


def _source_hash(text: str) -> str:
    return hashlib.sha256((text.rstrip() + "\n").encode("utf-8")).hexdigest()


def _write_codex_adapter(
    project_root: Path, directory: str, source_path: str, source_text: str, source_hash: str
) -> None:
    adapter_dir = project_root / ".codex" / "skills" / directory
    adapter_dir.mkdir(parents=True, exist_ok=True)
    adapter_dir.joinpath("SKILL.md").write_text(
        "\n".join(
            [
                "---",
                f"name: {directory}",
                "description: Test skill.",
                "---",
                "<!-- GTKB-CODEX-SKILL-ADAPTER",
                "Generated: true",
                "Generated by: scripts/generate_codex_skill_adapters.py",
                f"Canonical source: {source_path}",
                f"Canonical source sha256: {source_hash}",
                "Generated at: 2026-05-06T00:00:00Z",
                "Do not edit this adapter directly. Edit the canonical source and regenerate.",
                "GTKB-CODEX-SKILL-ADAPTER -->",
                "",
                "# Adapter",
                "",
                source_text,
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_registry(project_root: Path, body: str) -> None:
    registry_path = project_root / "config" / "agent-control" / "harness-capability-registry.toml"
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        "\n".join(
            [
                'registry_id = "test-registry"',
                'purpose = "test"',
                body.strip(),
                "",
            ]
        ),
        encoding="utf-8",
    )


def test_codex_fallback_is_degraded_not_missing(tmp_path: Path) -> None:
    module = _load_module()
    _write_skill(tmp_path, "review")
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = ".claude/skills/review/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/review/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert report.counts == {"DEGRADED": 1}
    assert report.results[0].state == "DEGRADED"


def test_required_missing_native_surface_fails(tmp_path: Path) -> None:
    module = _load_module()
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = ".claude/skills/review/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/review/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="claude", role="loyal-opposition")

    assert report.overall_status == "FAIL"
    assert report.counts == {"MISSING": 1}
    assert report.results[0].state == "MISSING"


def test_generated_adapter_passes_when_hash_matches(tmp_path: Path) -> None:
    module = _load_module()
    source_path = ".claude/skills/review/SKILL.md"
    source_text = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n"
    source_hash = _source_hash(source_text)
    skill_dir = tmp_path / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(source_text, encoding="utf-8")
    _write_codex_adapter(tmp_path, "review", source_path, source_text, source_hash)
    _write_registry(
        tmp_path,
        f"""
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = "{source_path}"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = "{source_path}"
status = "native"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = "{source_path}"
source_sha256 = "{source_hash}"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "PASS"
    assert report.counts == {"PASS": 1}
    assert report.results[0].state == "PASS"


def test_generated_adapter_reports_stale_when_source_hash_changes(tmp_path: Path) -> None:
    module = _load_module()
    source_path = ".claude/skills/review/SKILL.md"
    original_source = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n"
    original_hash = _source_hash(original_source)
    changed_source = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n\nChanged.\n"
    skill_dir = tmp_path / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(changed_source, encoding="utf-8")
    _write_codex_adapter(tmp_path, "review", source_path, original_source, original_hash)
    _write_registry(
        tmp_path,
        f"""
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = "{source_path}"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = "{source_path}"
status = "native"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = "{source_path}"
source_sha256 = "{original_hash}"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert report.counts == {"STALE": 1}
    assert report.results[0].state == "STALE"


def test_project_skill_not_declared_in_registry_is_extra(tmp_path: Path) -> None:
    module = _load_module()
    _write_skill(tmp_path, "tracked")
    _write_skill(tmp_path, "untracked", name="untracked-alias")
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.tracked"
kind = "skill"
canonical_name = "tracked"
canonical_source = ".claude/skills/tracked/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "baseline"

[capabilities.claude]
surface = ".claude/skills/tracked/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/tracked/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="claude", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert {extra.name for extra in report.extras} == {"untracked", "untracked-alias"}


def test_repository_registry_covers_project_skills() -> None:
    module = _load_module()

    report = module.check_harness_parity(REPO_ROOT, harness="claude", include_all=True)

    assert not report.errors
    assert not report.extras
    assert report.overall_status == "PASS"
