from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "check_harness_parity.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("check_harness_parity", SCRIPT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["check_harness_parity"] = module
    spec.loader.exec_module(module)
    return module


def _write_skill(project_root: Path, directory: str, name: str | None = None) -> None:
    skill_dir = project_root / ".claude" / "skills" / directory
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_name = name or directory
    skill_dir.joinpath("SKILL.md").write_text(
        f"---\nname: {skill_name}\ndescription: Test skill.\n---\n\n# {skill_name}\n",
        encoding="utf-8",
    )


def _source_hash(text: str) -> str:
    return hashlib.sha256((text.rstrip() + "\n").encode("utf-8")).hexdigest()


def _write_codex_adapter(
    project_root: Path, directory: str, source_path: str, source_text: str, source_hash: str
) -> None:
    adapter_dir = project_root / ".codex" / "skills" / directory
    adapter_dir.mkdir(parents=True, exist_ok=True)
    marker = "\n".join(
        [
            "<!-- GTKB-CODEX-SKILL-ADAPTER",
            "Generated: true",
            "Generated by: scripts/generate_codex_skill_adapters.py",
            f"Canonical source: {source_path}",
            f"Canonical source sha256: {source_hash}",
            "Generated at: 2026-05-06T00:00:00Z",
            "Do not edit this adapter directly. Edit the canonical source and regenerate.",
            "GTKB-CODEX-SKILL-ADAPTER -->",
            "",
        ]
    )
    closing = source_text.find("\n---\n", 3)
    assert closing != -1
    insert_at = closing + len("\n---\n")
    rendered = source_text[:insert_at] + marker + source_text[insert_at:]
    adapter_dir.joinpath("SKILL.md").write_text(rendered, encoding="utf-8")


def _build_adapter_case(project_root: Path, module, family: str):
    source_path = ".claude/skills/review/SKILL.md"
    source_text = "---\nname: review\ndescription: Test skill.\n---\n\nDeny protected mutation.\n"
    source_hash = _source_hash(source_text)
    source_file = project_root / source_path
    source_file.parent.mkdir(parents=True, exist_ok=True)
    source_file.write_text(source_text, encoding="utf-8")
    capability = {
        "id": "skill.review",
        "kind": "skill",
        "canonical_name": "review",
        "canonical_source": source_path,
        "required_for_roles": ["prime-builder"],
        "parity_class": "required",
    }
    common = {
        "capability_id": "skill.review",
        "canonical_name": "review",
        "source_relative_path": source_path,
        "source_sha256": source_hash,
    }
    generated_at = "2026-05-06T00:00:00Z"

    if family == "codex":
        surface = ".codex/skills/review/SKILL.md"
        adapter = module.codex_adapter_generator.SkillAdapter(adapter_relative_path=surface, **common)
        rendered = module.codex_adapter_generator.render_adapter(source_text, adapter, generated_at=generated_at)
        harness = "codex"
        manifests = None
        capability[harness] = {"surface": surface, "status": "adapter", "adapter_source": source_path}
    elif family == "antigravity":
        surface = ".agent/skills/review/SKILL.md"
        adapter = module.antigravity_adapter_generator.SkillAdapter(adapter_relative_path=surface, **common)
        rendered = module.antigravity_adapter_generator.render_adapter(source_text, adapter, generated_at=generated_at)
        harness = "antigravity"
        manifests = None
        capability[harness] = {"surface": surface, "status": "adapter", "adapter_source": source_path}
    elif family == "api":
        surface = ".api-harness/skills/review/SKILL.md"
        adapter = module.api_adapter_generator.ApiSkillAdapter(
            adapter_relative_path=surface,
            description="Test skill.",
            **common,
        )
        rendered = module.api_adapter_generator.render_adapter(adapter, generated_at=generated_at)
        harness = "ollama"
        manifests = {
            harness: {"skill.review": {"surface": surface, "status": "adapter", "adapter_source": source_path}}
        }
    else:
        raise AssertionError(f"unsupported test family: {family}")

    adapter_path = project_root / surface
    adapter_path.parent.mkdir(parents=True, exist_ok=True)
    adapter_path.write_text(rendered, encoding="utf-8")
    return capability, harness, manifests, source_file, adapter_path


def _adapter_status(project_root: Path, module, family: str):
    capability, harness, manifests, _source_file, _adapter_path = _build_adapter_case(project_root, module, family)
    return module._status_for_surface(project_root, capability, harness, manifests)


def _write_registry(project_root: Path, body: str) -> None:
    registry_path = project_root / "config" / "agent-control" / "harness-capability-registry.toml"
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        "\n".join(
            [
                'registry_id = "test-registry"',
                'purpose = "test"',
                body.strip(),
                "",
            ]
        ),
        encoding="utf-8",
    )


def test_alibaba_managed_skill_adoption_review_is_truthfully_unsupported(monkeypatch, tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "H",
                "harness_name": "alibaba-cloud-studio",
                "harness_type": "claude",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            }
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.managed-skill-adoption-review"
kind = "skill"
canonical_name = "managed-skill-adoption-review"
canonical_source = ".claude/skills/managed-skill-adoption-review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.alibaba-cloud-studio]
status = "unsupported"
reason = "Alibaba Cloud Studio is a provider harness and does not execute repo-local managed skill adapters; structural managed-artifact review remains assigned to native/adapter-capable harnesses."
""",
    )
    monkeypatch.setattr(module, "KNOWN_HARNESSES", module._load_known_harnesses_from_projection(tmp_path))

    report = module.check_harness_parity(
        tmp_path,
        harness="alibaba-cloud-studio",
        role="loyal-opposition",
    )
    target = [result for result in report.results if result.capability_id == "skill.managed-skill-adoption-review"]

    assert len(target) == 1
    assert target[0].state == "UNSUPPORTED"
    assert "does not execute repo-local managed skill adapters" in target[0].note


def test_codex_fallback_is_degraded_not_missing(tmp_path: Path) -> None:
    module = _load_module()
    _write_skill(tmp_path, "review")
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = ".claude/skills/review/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/review/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert report.counts == {"DEGRADED": 1}
    assert report.results[0].state == "DEGRADED"


def test_required_missing_native_surface_fails(tmp_path: Path) -> None:
    module = _load_module()
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = ".claude/skills/review/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/review/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="claude", role="loyal-opposition")

    assert report.overall_status == "FAIL"
    assert report.counts == {"MISSING": 1}
    assert report.results[0].state == "MISSING"


def test_generated_adapter_passes_when_hash_matches(tmp_path: Path) -> None:
    module = _load_module()
    source_path = ".claude/skills/review/SKILL.md"
    source_text = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n"
    source_hash = _source_hash(source_text)
    skill_dir = tmp_path / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(source_text, encoding="utf-8")
    _write_codex_adapter(tmp_path, "review", source_path, source_text, source_hash)
    _write_registry(
        tmp_path,
        f"""
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = "{source_path}"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = "{source_path}"
status = "native"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = "{source_path}"
source_sha256 = "{source_hash}"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "PASS"
    assert report.counts == {"PASS": 1}
    assert report.results[0].state == "PASS"


def test_generated_adapter_reports_stale_when_source_hash_changes(tmp_path: Path) -> None:
    module = _load_module()
    source_path = ".claude/skills/review/SKILL.md"
    original_source = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n"
    original_hash = _source_hash(original_source)
    changed_source = "---\nname: review\ndescription: Test skill.\n---\n\n# review\n\nChanged.\n"
    skill_dir = tmp_path / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(changed_source, encoding="utf-8")
    _write_codex_adapter(tmp_path, "review", source_path, original_source, original_hash)
    _write_registry(
        tmp_path,
        f"""
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = "{source_path}"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = "{source_path}"
status = "native"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = "{source_path}"
source_sha256 = "{original_hash}"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert report.counts == {"STALE": 1}
    assert report.results[0].state == "STALE"


def test_generated_adapter_reports_stale_when_semantics_conflict_with_current_hash(tmp_path: Path) -> None:
    module = _load_module()
    source_path = ".claude/skills/review/SKILL.md"
    source_text = "---\nname: review\ndescription: Test skill.\n---\n\nDeny protected mutation.\n"
    source_hash = _source_hash(source_text)
    skill_dir = tmp_path / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(source_text, encoding="utf-8")
    _write_codex_adapter(tmp_path, "review", source_path, source_text, source_hash)
    adapter_path = tmp_path / ".codex" / "skills" / "review" / "SKILL.md"
    adapter_path.write_text(
        adapter_path.read_text(encoding="utf-8").replace("Deny protected mutation.", "Allow protected mutation."),
        encoding="utf-8",
    )
    _write_registry(
        tmp_path,
        f"""
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = "{source_path}"
required_for_roles = ["prime-builder"]
parity_class = "required"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = "{source_path}"
source_sha256 = "{source_hash}"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="prime-builder")

    assert report.counts == {"STALE": 1}
    assert report.results[0].state == "STALE"
    assert "semantics do not match" in report.results[0].note


@pytest.mark.parametrize("family", ["codex", "antigravity", "api"])
def test_semantic_adapter_families_pass_for_exact_generator_output(tmp_path: Path, family: str) -> None:
    module = _load_module()

    result = _adapter_status(tmp_path, module, family)

    assert result.state == "PASS"
    assert result.note == "Generated adapter matches the canonical source."


@pytest.mark.parametrize("family", ["codex", "antigravity", "api"])
def test_semantic_adapter_families_reject_hash_current_body_tamper(tmp_path: Path, family: str) -> None:
    module = _load_module()
    capability, harness, manifests, _source_file, adapter_path = _build_adapter_case(tmp_path, module, family)
    original = adapter_path.read_text(encoding="utf-8")
    if family == "api":
        tampered = original.replace("compact discovery pointer", "full canonical source copy")
    else:
        tampered = original.replace("Deny protected mutation.", "Allow protected mutation.")
    assert tampered != original
    adapter_path.write_text(tampered, encoding="utf-8")

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert "semantics do not match" in result.note


def test_semantic_adapter_rejects_missing_generator_identity(tmp_path: Path) -> None:
    module = _load_module()
    capability, harness, manifests, _source_file, adapter_path = _build_adapter_case(tmp_path, module, "codex")
    adapter_path.write_text(
        "\n".join(
            line
            for line in adapter_path.read_text(encoding="utf-8").splitlines()
            if not line.startswith("Generated by:")
        ),
        encoding="utf-8",
    )

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert "generator identity" in result.note


def test_semantic_adapter_rejects_missing_generation_timestamp(tmp_path: Path) -> None:
    module = _load_module()
    capability, harness, manifests, _source_file, adapter_path = _build_adapter_case(tmp_path, module, "antigravity")
    adapter_path.write_text(
        "\n".join(
            line
            for line in adapter_path.read_text(encoding="utf-8").splitlines()
            if not line.startswith("Generated at:")
        ),
        encoding="utf-8",
    )

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert "generation timestamp" in result.note


def test_semantic_adapter_rejects_alias_confused_marker_identity(tmp_path: Path) -> None:
    module = _load_module()
    capability, harness, manifests, _source_file, adapter_path = _build_adapter_case(tmp_path, module, "antigravity")
    adapter_path.write_text(
        adapter_path.read_text(encoding="utf-8").replace("GTKB-ANTIGRAVITY-SKILL-ADAPTER", "GTKB-CODEX-SKILL-ADAPTER"),
        encoding="utf-8",
    )

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert "generator identity" in result.note


def test_semantic_adapter_reports_api_reconstruction_failure(tmp_path: Path) -> None:
    module = _load_module()
    capability, harness, manifests, source_file, adapter_path = _build_adapter_case(tmp_path, module, "api")
    invalid_source = "---\nname: review\n---\n\nDeny protected mutation.\n"
    invalid_hash = _source_hash(invalid_source)
    source_file.write_text(invalid_source, encoding="utf-8")
    adapter_path.write_text(
        adapter_path.read_text(encoding="utf-8").replace(
            _source_hash("---\nname: review\ndescription: Test skill.\n---\n\nDeny protected mutation.\n"), invalid_hash
        ),
        encoding="utf-8",
    )

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert "could not be rendered" in result.note


def test_semantic_adapter_reports_renderer_failure(tmp_path: Path, monkeypatch) -> None:
    module = _load_module()
    capability, harness, manifests, _source_file, _adapter_path = _build_adapter_case(tmp_path, module, "codex")
    monkeypatch.setattr(
        module.codex_adapter_generator,
        "render_adapter",
        lambda *_args, **_kwargs: (_ for _ in ()).throw(ValueError("renderer failed")),
    )

    result = module._status_for_surface(tmp_path, capability, harness, manifests)

    assert result.state == "STALE"
    assert result.note == "Canonical adapter semantics could not be rendered: renderer failed"


def test_project_skill_not_declared_in_registry_is_extra(tmp_path: Path) -> None:
    module = _load_module()
    _write_skill(tmp_path, "tracked")
    _write_skill(tmp_path, "untracked", name="untracked-alias")
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.tracked"
kind = "skill"
canonical_name = "tracked"
canonical_source = ".claude/skills/tracked/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "baseline"

[capabilities.claude]
surface = ".claude/skills/tracked/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".claude/skills/tracked/SKILL.md"
status = "fallback"
fallback = "Read the project skill."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="claude", role="loyal-opposition")

    assert report.overall_status == "WARN"
    assert {extra.name for extra in report.extras} == {"untracked", "untracked-alias"}


def test_unsupported_harness_surface_is_warn_not_missing(tmp_path: Path) -> None:
    module = _load_module()
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "hook.prompt-only"
kind = "hook"
canonical_name = "prompt-only"
canonical_source = ".claude/hooks/prompt-only.py"
required_for_roles = ["prime-builder"]
parity_class = "required"

[capabilities.codex]
status = "unsupported"
reason = "Codex has no matching prompt-only hook surface."
""",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="prime-builder")

    assert report.overall_status == "WARN"
    assert report.counts == {"UNSUPPORTED": 1}
    assert report.results[0].state == "UNSUPPORTED"
    assert "no matching prompt-only hook" in report.results[0].note


def test_role_scope_defaults_to_assigned_harness_population(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "A",
                "harness_name": "codex",
                "harness_type": "codex",
                "status": "active",
                "role": ["prime-builder"],
                "version": 1,
            },
            {
                "id": "C",
                "harness_name": "antigravity",
                "harness_type": "antigravity",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            },
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["prime-builder", "loyal-opposition"]
parity_class = "baseline"

[capabilities.codex]
status = "unsupported"
reason = "test"

[capabilities.antigravity]
status = "unsupported"
reason = "test"
""",
    )

    report = module.check_harness_parity(tmp_path, role="prime-builder")

    assert report.selected_harnesses == ["codex"]
    capability_results = [result for result in report.results if not result.capability_id.startswith("fleet.")]
    coverage_results = [result for result in report.results if result.capability_id.startswith("fleet.")]
    assert {result.harness for result in capability_results} == {"codex"}
    assert [(result.capability_id, result.state) for result in coverage_results] == [
        ("fleet.role-coverage.prime-builder", "PASS")
    ]


def test_universal_capabilities_keep_active_population_under_role_scope(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "A",
                "harness_name": "codex",
                "harness_type": "codex",
                "status": "active",
                "role": ["prime-builder"],
                "version": 1,
            },
            {
                "id": "C",
                "harness_name": "antigravity",
                "harness_type": "antigravity",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            },
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "hook.shared-session"
kind = "hook"
canonical_name = "shared-session"
canonical_source = ".claude/hooks/shared-session.py"
required_for_roles = ["prime-builder", "loyal-opposition"]
parity_class = "shared"
applicability = "universal"

[capabilities.codex]
status = "unsupported"
reason = "test"

[capabilities.antigravity]
status = "unsupported"
reason = "test"
""",
    )

    report = module.check_harness_parity(tmp_path, role="prime-builder")

    assert report.selected_harnesses == ["codex"]
    shared_results = [result for result in report.results if result.capability_id == "hook.shared-session"]
    assert {result.harness for result in shared_results} == {"codex", "antigravity"}


def test_explicit_harness_overrides_assigned_role_scope_for_diagnostics(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "A",
                "harness_name": "codex",
                "harness_type": "codex",
                "status": "active",
                "role": ["prime-builder"],
                "version": 1,
            },
            {
                "id": "C",
                "harness_name": "antigravity",
                "harness_type": "antigravity",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            },
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["prime-builder", "loyal-opposition"]
parity_class = "baseline"

[capabilities.codex]
status = "unsupported"
reason = "test"

[capabilities.antigravity]
status = "unsupported"
reason = "test"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="antigravity", role="prime-builder")

    assert report.selected_harnesses == ["antigravity"]
    assert {result.harness for result in report.results} == {"antigravity"}


def test_fleet_role_coverage_reports_uncovered_operating_role(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "C",
                "harness_name": "antigravity",
                "harness_type": "antigravity",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            }
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.antigravity]
status = "unsupported"
reason = "test"
""",
    )

    report = module.check_harness_parity(tmp_path, include_all=True)

    coverage_by_role = {
        result.capability_id: result
        for result in report.results
        if result.capability_id.startswith("fleet.role-coverage.")
    }
    assert coverage_by_role["fleet.role-coverage.prime-builder"].state == "MISSING"
    assert "No active harness is assigned `prime-builder`" in coverage_by_role["fleet.role-coverage.prime-builder"].note
    assert coverage_by_role["fleet.role-coverage.loyal-opposition"].state == "PASS"


def test_activity_envelope_projection_accepts_compact_provider_without_transcripts() -> None:
    module = _load_module()
    registry = {
        "harnesses": {
            "codex": {
                "activity_envelope_projection_mode": "native",
                "compact_result_envelope_mode": "native",
                "compact_session_envelope_mode": "native",
                "full_transcript_archive_required": False,
            },
            "openrouter": {
                "activity_envelope_projection_mode": "compact-provider",
                "compact_result_envelope_mode": "compact-provider",
                "compact_session_envelope_mode": "compact-provider",
                "full_transcript_archive_required": False,
            },
        }
    }

    results = module._activity_envelope_projection_results(["codex", "openrouter"], registry)

    assert len(results) == 8
    assert all(result.state == "PASS" for result in results)
    openrouter_modes = {
        result.capability_id: result.configured_status for result in results if result.harness == "openrouter"
    }
    assert openrouter_modes["activity_envelope.activity_envelope_projection_mode"] == "compact-provider"
    assert openrouter_modes["activity_envelope.full_transcript_archive_independence"] == "false"


def test_activity_envelope_projection_missing_field_fails_required_row() -> None:
    module = _load_module()
    registry = {
        "harnesses": {
            "ollama": {
                "activity_envelope_projection_mode": "compact-provider",
                "compact_session_envelope_mode": "compact-provider",
                "full_transcript_archive_required": False,
            }
        }
    }

    results = module._activity_envelope_projection_results(["ollama"], registry)

    missing = [result for result in results if result.state == "MISSING"]
    assert len(missing) == 1
    assert missing[0].capability_id == "activity_envelope.compact_result_envelope_mode"


def test_api_skill_manifest_does_not_synthesize_hook_support(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "D",
                "harness_name": "ollama",
                "harness_type": "ollama",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            }
        ],
    )
    hook_path = tmp_path / ".claude" / "hooks" / "prompt-only.py"
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    hook_path.write_text("print('hook')\n", encoding="utf-8")
    manifest_path = tmp_path / ".api-harness" / "skills" / "MANIFEST.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"adapters": []}), encoding="utf-8")
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "hook.prompt-only"
kind = "hook"
canonical_name = "prompt-only"
canonical_source = ".claude/hooks/prompt-only.py"
required_for_roles = ["loyal-opposition"]
parity_class = "shared"

[harnesses.ollama]
skill_adapter_manifest = ".api-harness/skills/MANIFEST.json"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="ollama", role="loyal-opposition")

    assert report.results[0].state == "UNSUPPORTED"
    assert "Skill adapter manifests do not prove hook registration" in report.results[0].note


def test_typed_parity_waiver_classifies_missing_surface_as_unsupported(tmp_path: Path) -> None:
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "B",
                "harness_name": "claude",
                "harness_type": "claude",
                "status": "active",
                "role": ["prime-builder"],
                "version": 1,
            }
        ],
    )
    _write_registry(
        tmp_path,
        """
[[capabilities]]
id = "hook.codex-only"
kind = "hook"
canonical_name = "codex-only"
canonical_source = ".codex/gtkb-hooks/codex-only.cmd"
required_for_roles = ["prime-builder"]
parity_class = "shared"

[capabilities.codex]
surface = ".codex/gtkb-hooks/codex-only.cmd"
status = "native"

[[parity_waivers]]
capability_id = "hook.codex-only"
harness = "claude"
reason_class = "harness-surface-difference"
rationale = "Codex-only hook surface."
owner_approval_ref = "DELIB-TEST"
review_trigger = "test"
""",
    )

    report = module.check_harness_parity(tmp_path, harness="claude", role="prime-builder")

    assert report.results[0].state == "UNSUPPORTED"
    assert report.results[0].configured_status == "waived:harness-surface-difference"
    assert "DELIB-TEST" in report.results[0].note


def test_repository_registry_covers_project_skills() -> None:
    module = _load_module()

    report = module.check_harness_parity(REPO_ROOT, harness="claude", include_all=True)

    assert not report.errors
    assert not report.extras
    assert not [result for result in report.results if result.state == "MISSING"]
    assert report.overall_status != "FAIL"


def test_repository_registry_has_no_unclassified_missing_rows() -> None:
    module = _load_module()

    report = module.check_harness_parity(REPO_ROOT, include_all=True)
    missing = [result for result in report.results if result.state == "MISSING"]

    assert not report.errors
    assert not missing
    assert report.overall_status != "FAIL"


def test_advisory_skill_parity_rows_are_enforced_when_surfaces_exist() -> None:
    module = _load_module()
    skill_names = ("advisory-proposal", "advisory-intake")
    registry, _ = module.load_registry(REPO_ROOT)
    capabilities = {
        str(item.get("canonical_name")): item
        for item in registry.get("capabilities", [])
        if isinstance(item, dict) and item.get("kind") == "skill"
    }
    implemented = [
        name
        for name in skill_names
        if (REPO_ROOT / ".claude" / "skills" / name / "SKILL.md").is_file()
        or (REPO_ROOT / ".codex" / "skills" / name / "SKILL.md").is_file()
    ]

    if not implemented and not any(name in capabilities for name in skill_names):
        for slug, test_id in (
            ("gtkb-wi5055-advisory-proposal-skill", "TEST-11293"),
            ("gtkb-wi5056-prime-advisory-intake-skill", "TEST-11294"),
        ):
            proposal = (REPO_ROOT / "bridge" / f"{slug}-001.md").read_text(encoding="utf-8")
            verdict = (REPO_ROOT / "bridge" / f"{slug}-002.md").read_text(encoding="utf-8")
            assert verdict.lstrip().startswith("GO")
            assert f"Linked manual test: {test_id}" in proposal
        return

    missing_registry = [name for name in implemented if name not in capabilities]
    assert not missing_registry, f"implemented advisory skills missing registry rows: {missing_registry}"

    report = module.check_harness_parity(REPO_ROOT, harness="codex", include_all=True)
    results = {
        result.capability_name: result
        for result in report.results
        if result.capability_name in set(implemented) and result.harness == "codex"
    }
    assert set(results) == set(implemented)
    non_pass = {name: result for name, result in results.items() if result.state != "PASS"}
    assert not non_pass, f"advisory skill Codex parity must pass: {non_pass}"


# WI-4317 / WI-4318 capability-floor mode tests (Child 1 foundation per
# bridge/gtkb-ollama-integration-phase-1-foundation-010.md GO).


def _write_projection(project_root: Path, harnesses_list: list[dict]) -> None:
    """Helper: write a harness-state/harness-registry.json projection fixture."""
    hs_dir = project_root / "harness-state"
    hs_dir.mkdir(parents=True, exist_ok=True)
    doc = {
        "description": "test fixture projection",
        "generated_at": "2026-06-05T00:00:00Z",
        "harnesses": harnesses_list,
        "schema_version": 1,
        "source_of_truth": "test fixture",
    }
    (hs_dir / "harness-registry.json").write_text(json.dumps(doc, indent=2), encoding="utf-8")


def test_known_harnesses_data_driven_from_projection(monkeypatch, tmp_path: Path) -> None:
    """KNOWN_HARNESSES loader sources from harness-state/harness-registry.json projection.

    F4 fix (per Codex NO-GO at gtkb-ollama-integration-phase-1-foundation-004.md):
    uses scripts.harness_projection_reader, not a direct harness-identities.json read.
    """
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "A",
                "harness_name": "codex",
                "harness_type": "codex",
                "status": "active",
                "role": ["loyal-opposition"],
                "version": 1,
            },
            {
                "id": "B",
                "harness_name": "claude",
                "harness_type": "claude",
                "status": "active",
                "role": ["prime-builder"],
                "version": 1,
            },
            {
                "id": "C",
                "harness_name": "antigravity",
                "harness_type": "antigravity",
                "status": "registered",
                "role": ["prime-builder"],
                "version": 1,
            },
            {
                "id": "D",
                "harness_name": "ollama",
                "harness_type": "ollama",
                "status": "registered",
                "role": [],
                "version": 1,
            },
        ],
    )
    monkeypatch.setattr(module, "PROJECT_ROOT", tmp_path)
    result = module._load_known_harnesses_from_projection()
    assert result == ("antigravity", "claude", "codex", "ollama")


def test_known_harnesses_fallback_on_empty_projection(monkeypatch, tmp_path: Path) -> None:
    """Empty harnesses array → falls back to baseline tuple."""
    module = _load_module()
    _write_projection(tmp_path, [])
    monkeypatch.setattr(module, "PROJECT_ROOT", tmp_path)
    result = module._load_known_harnesses_from_projection()
    assert result == ("claude", "codex")


def test_known_harnesses_fallback_on_missing_projection(monkeypatch, tmp_path: Path) -> None:
    """Missing projection file → fail-safe loader returns empty doc → fallback to baseline."""
    module = _load_module()
    (tmp_path / "harness-state").mkdir()  # parent exists, file absent
    monkeypatch.setattr(module, "PROJECT_ROOT", tmp_path)
    result = module._load_known_harnesses_from_projection()
    assert result == ("claude", "codex")


def test_capability_floor_for_registered_no_role_harness(monkeypatch, tmp_path: Path) -> None:
    """Registered/no-active-role harness with full floor → 6 PASS CapabilityResults."""
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "D",
                "harness_name": "ollama",
                "harness_type": "ollama",
                "status": "registered",
                "role": [],
                "version": 1,
            }
        ],
    )
    monkeypatch.setattr(module, "PROJECT_ROOT", tmp_path)
    assert module._harness_lifecycle_class("ollama", tmp_path) == "registered_no_role"
    registry = {
        "harnesses": {
            "ollama": {
                "bridge_compliance_gate_respect": True,
                "root_boundary_respect": True,
                "author_metadata_env_var_setting": True,
                "destructive_gate_delegation": True,
                "advertised_tool_subset": ["Read", "Write", "Edit", "Grep", "Glob", "Bash"],
                "tool_guard_adapter_fail_closed": True,
            }
        }
    }
    results = module._evaluate_capability_floor("ollama", registry)
    assert len(results) == 6
    assert all(r.state == "PASS" for r in results)
    assert all(r.parity_class == "required" for r in results)
    assert {r.capability_id for r in results} == {
        "capability_floor.bridge_compliance_gate_respect",
        "capability_floor.root_boundary_respect",
        "capability_floor.author_metadata_env_var_setting",
        "capability_floor.destructive_gate_delegation",
        "capability_floor.advertised_tool_subset",
        "capability_floor.tool_guard_adapter_fail_closed",
    }


def test_capability_floor_missing_floor_returns_MISSING(tmp_path: Path) -> None:
    """Registered harness without [harnesses.<name>] block → 6 MISSING CapabilityResults."""
    module = _load_module()
    registry = {"harnesses": {}}  # No ollama floor
    results = module._evaluate_capability_floor("ollama", registry)
    assert len(results) == 6
    assert all(r.state == "MISSING" for r in results)
    assert all(r.parity_class == "required" for r in results)
    for r in results:
        assert "not declared" in r.note


def test_cli_exits_nonzero_when_capability_floor_missing(monkeypatch, tmp_path: Path) -> None:
    """F8 spec-derivation: registered/no-role harness without floor → CLI exit code 1.

    Per Codex NO-GO at gtkb-ollama-integration-phase-1-foundation-008.md, the capability-floor
    enforcement must reach the CLI exit path. CapabilityResult(parity_class='required', state='MISSING')
    triggers _overall_status() FAIL, which check_harness_parity.py:541 maps to exit code 1.
    """
    module = _load_module()
    _write_projection(
        tmp_path,
        [
            {
                "id": "D",
                "harness_name": "ollama",
                "harness_type": "ollama",
                "status": "registered",
                "role": [],
                "version": 1,
            }
        ],
    )
    monkeypatch.setattr(module, "PROJECT_ROOT", tmp_path)
    # Write a capability registry WITHOUT [harnesses.ollama] block
    reg_dir = tmp_path / "config" / "agent-control"
    reg_dir.mkdir(parents=True, exist_ok=True)
    (reg_dir / "harness-capability-registry.toml").write_text(
        'schema_version = 1\nregistry_id = "test"\npurpose = "test"\nlast_updated = "2026-06-05"\n',
        encoding="utf-8",
    )
    report = module.check_harness_parity(tmp_path, harness="ollama")
    assert report.overall_status == "FAIL"
    # 6 MISSING required CapabilityResults for the absent floor
    missing_required = [
        r for r in report.results if r.state == "MISSING" and r.parity_class == "required" and r.harness == "ollama"
    ]
    assert len(missing_required) == 6
