"""The ``gtkb-sweep-commit`` skill instructs only authorized Git operations.

WI-6682 / ``bridge/gtkb-wi6682-sweep-commit-skill-retirement`` (GO at ``-002``).

WHY THIS TEST EXISTS. The skill previously instructed ``git add -A``, a
``git update-index`` fallback, and a direct commit. Every one of those is refused
at the PreToolUse boundary by ``_direct_git_effect`` in
``scripts/implementation_start_gate.py``, which blocks any Git subcommand outside
``DIRECT_GIT_READ_ONLY_SUBCOMMANDS``. More importantly, the whole-worktree premise
is forbidden by owner decision ``DELIB-202666332``, which authorizes local commits
only for independently VERIFIED scopes that are mechanically isolated, and
explicitly does not authorize a broad sweep capturing unverified, unowned,
modified-historical, or concurrent bytes. ``WI-5112`` records the concrete
incident class: whole-file staging corrupts cross-work-item commits on a
commingled worktree.

CRITERION. The canonical baseline skill must not instruct a blocked Git verb, and
must route commits through the per-work-item governed lifecycle.

METHOD NOTE — WHY THE ASSERTION IS ABSENCE, NOT PROHIBITION. The skill is not
allowed to say "do not run ``git add -A``". Per
``.harness-baseline-configuration/rules/prime-builder.md`` § "Correcting Direction
- Purge Before Probative Language" (authority ``DELIB-20260806011917``), obsolete
direction is deleted at the source rather than counter-instructed, because naming
a forbidden operation teaches it and establishes a competing authority in the
agent's model. A prohibition sentence would therefore both violate that rule and
fail this test. Absence is the correct and intended signal.

SCOPE. This test asserts against the canonical baseline source only. The harness
projections are generated outputs regenerated by ``gt harness project <harness>``
per ``GOV-HARNESS-NEUTRAL-BASELINE-001``; asserting against the baseline keeps the
test valid independently of projection timing.

Copyright 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC.
All rights reserved.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SKILL_PATH = PROJECT_ROOT / ".harness-baseline-configuration" / "skills" / "gtkb-sweep-commit" / "SKILL.md"

# Git invocations refused by ``_direct_git_effect`` for this skill's purposes.
# Each entry is (label, compiled pattern).
BLOCKED_GIT_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("git add -A", re.compile(r"git\s+add\s+(?:[^\n]*\s)?-A\b")),
    ("git add --all", re.compile(r"git\s+add\s+(?:[^\n]*\s)?--all\b")),
    ("git add -u", re.compile(r"git\s+add\s+(?:[^\n]*\s)?-u\b")),
    ("git add .", re.compile(r"git\s+add\s+\.(?:\s|$)")),
    ("git update-index", re.compile(r"git\s+update-index\b")),
    ("git commit", re.compile(r"git\s+commit\b")),
)

# The governed replacement path: work-item-scoped lifecycle operations.
REQUIRED_LIFECYCLE_TOKENS: tuple[str, ...] = (
    "groundtruth_kb.git_lifecycle",
    "preserve --work-item-id",
)


@pytest.fixture(scope="module")
def skill_text() -> str:
    assert SKILL_PATH.is_file(), f"canonical baseline skill missing: {SKILL_PATH}"
    return SKILL_PATH.read_text(encoding="utf-8")


@pytest.mark.parametrize(("label", "pattern"), BLOCKED_GIT_PATTERNS, ids=lambda v: v if isinstance(v, str) else "")
def test_skill_instructs_no_blocked_git_verb(skill_text: str, label: str, pattern: re.Pattern[str]) -> None:
    """No blocked Git invocation appears anywhere in the canonical skill."""
    match = pattern.search(skill_text)
    offset = match.start() if match else -1
    excerpt = match.group(0) if match else ""
    assert match is None, (
        f"canonical gtkb-sweep-commit skill contains blocked Git invocation {label!r} "
        f"at offset {offset}: {excerpt!r}. "
        "Commits must route through `python -m groundtruth_kb.git_lifecycle preserve "
        "--work-item-id <WI-NNNN>` per DELIB-202666332. Do not add a prohibition "
        "sentence naming the verb; delete the instruction (prime-builder.md "
        "'Purge Before Probative Language')."
    )


@pytest.mark.parametrize("token", REQUIRED_LIFECYCLE_TOKENS)
def test_skill_routes_commits_through_governed_lifecycle(skill_text: str, token: str) -> None:
    """The skill names the per-work-item governed lifecycle as the commit path."""
    assert token in skill_text, (
        f"canonical gtkb-sweep-commit skill does not cite {token!r}. The governed "
        "commit path is work-item scoped: create / attach / preserve via "
        "`python -m groundtruth_kb.git_lifecycle`."
    )


def test_skill_cites_governing_owner_decision(skill_text: str) -> None:
    """The constraint travels with the procedure rather than living only in the archive."""
    assert "DELIB-202666332" in skill_text, (
        "canonical gtkb-sweep-commit skill does not cite DELIB-202666332, the owner "
        "decision that authorizes exact per-scope finalization and withholds "
        "authorization for a broad sweep."
    )


def test_skill_description_does_not_advertise_whole_worktree_commit(skill_text: str) -> None:
    """The frontmatter description must not promise the forbidden capability.

    The description is the trigger surface: an operator asking to "commit
    everything" is routed by it. Advertising a whole-worktree commit sends them to
    a procedure that cannot run and invites a bypass attempt.
    """
    frontmatter = skill_text.split("---", 2)
    assert len(frontmatter) >= 3, "skill frontmatter block not found"
    description = frontmatter[1]
    forbidden_promise = re.compile(
        r"(?i)(?:sweep and locally commit all|commit all current non-ignored|"
        r"full-worktree cleanup commit)"
    )
    match = forbidden_promise.search(description)
    excerpt = match.group(0) if match else ""
    assert match is None, (
        "gtkb-sweep-commit frontmatter description advertises a whole-worktree "
        f"commit ({excerpt!r}), which DELIB-202666332 does "
        "not authorize. Describe the governed per-scope finalization instead."
    )
