"""Parity-checker support for full-body projections (WI-6267).

Landed by bridge/gtkb-wi6267-parity-projection-contract (REVISED at -003,
GO at -004). Maps to the four mechanisms the revision established:

- M1 marker-branch routing -> ``test_projection_engine_routes_to_own_marker``,
  ``test_manifest_only_harnesses_keep_the_api_branch``
- M2 generator resolution -> ``test_generator_resolves_from_registry_declaration``,
  ``test_stub_generator_map_is_unchanged``
- M3 marker grammar -> ``test_find_markers_parses_begin_end_grammar`` and the
  stub-grammar / absent-block companions
- M4 expected-content oracle -> ``test_projection_oracle_is_the_engine_plan``,
  ``test_tampered_body_is_detected``

The STALE-preserving tests are the load-bearing ones: a repair that only
demonstrates PASS has not shown it kept the true positive.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = PROJECT_ROOT / "scripts"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

_spec = importlib.util.spec_from_file_location("check_harness_parity", SCRIPTS_DIR / "check_harness_parity.py")
chp = importlib.util.module_from_spec(_spec)
sys.modules["check_harness_parity"] = chp
_spec.loader.exec_module(chp)

PROJECTION_HARNESS = "goose"
PROJECTION_MARKER = "GTKB-GOOSE-SKILL-ADAPTER"
STUB_MARKERS = (
    "GTKB-CODEX-SKILL-ADAPTER",
    "GTKB-ANTIGRAVITY-SKILL-ADAPTER",
    "GTKB-API-SKILL-ADAPTER",
    "GTKB-CURSOR-SKILL-ADAPTER",
)


def _projection_block(marker: str = PROJECTION_MARKER, digest: str = "a" * 64) -> str:
    """The grammar the projection engine emits (adapter_metadata_block)."""
    return (
        "<!--\n"
        f"{marker}-BEGIN\n"
        "Generated by: scripts/harness_projection/project_harness.py\n"
        f"Generated at: content-addressed {digest[:12]}\n"
        "Canonical source: .harness-baseline-configuration/skills/x/SKILL.md\n"
        f"Canonical source sha256: {digest}\n"
        f"{marker}-END\n"
        "-->\n"
    )


def _stub_block(marker: str = "GTKB-API-SKILL-ADAPTER", digest: str = "b" * 64) -> str:
    """The grammar the compact-stub generators emit."""
    return (
        f"<!-- {marker}\n"
        "Generated by: scripts/generate_api_skill_adapters.py\n"
        "Generated at: 1970-01-01T00:00:00Z\n"
        "Canonical source: .harness-baseline-configuration/skills/x/SKILL.md\n"
        f"Canonical source sha256: {digest}\n"
        f"{marker} -->\n"
    )


# --- M3: marker grammar -------------------------------------------------


def test_find_markers_parses_begin_end_grammar():
    """The projector's BEGIN/END block resolves; before WI-6267 it returned None."""
    text = "# Skill\n\nbody\n\n" + _projection_block()
    markers = chp._find_markers(text, PROJECTION_MARKER)
    assert markers is not None, "projection grammar must resolve for the correct marker"
    start_marker, end_marker = markers
    assert start_marker.endswith(f"{PROJECTION_MARKER}-BEGIN")
    assert end_marker.startswith(f"{PROJECTION_MARKER}-END")


def test_find_markers_parses_begin_end_grammar_without_expected_marker():
    """The generic discovery path resolves the projection grammar too."""
    text = "# Skill\n\nbody\n\n" + _projection_block()
    assert chp._find_markers(text) is not None


def test_find_markers_parses_stub_grammar_unchanged():
    """The stub contract is preserved for the harness families that still use it."""
    for marker in STUB_MARKERS:
        text = "# Skill\n\nbody\n\n" + _stub_block(marker)
        markers = chp._find_markers(text, marker)
        assert markers is not None, f"stub grammar regressed for {marker}"


def test_find_markers_returns_none_when_block_absent():
    """No block means no metadata - the gate must not invent one."""
    assert chp._find_markers("# Skill\n\nbody with no adapter block\n", PROJECTION_MARKER) is None
    assert chp._find_markers("# Skill\n\nbody with no adapter block\n") is None


def test_adapter_metadata_parsed_from_projection_grammar():
    digest = "c" * 64
    text = "# Skill\n\nbody\n\n" + _projection_block(digest=digest)
    metadata = chp._adapter_metadata(text, PROJECTION_MARKER)
    assert metadata["Generated by"] == "scripts/harness_projection/project_harness.py"
    assert metadata["Canonical source sha256"] == digest
    assert metadata["Generated at"], "the checker requires a non-empty generation stamp"


def test_strip_generated_block_removes_projection_block():
    body = "# Skill\n\nbody\n"
    text = body + "\n" + _projection_block()
    assert PROJECTION_MARKER not in chp._strip_generated_block(text, PROJECTION_MARKER)


# --- M1 / M2: routing and generator resolution --------------------------


def test_projection_engine_routes_to_own_marker():
    engines = chp._projection_engine_by_harness(PROJECT_ROOT)
    assert PROJECTION_HARNESS in engines
    assert engines[PROJECTION_HARNESS] == "scripts/harness_projection/project_harness.py"


def test_manifest_only_harnesses_keep_the_api_branch():
    """Harnesses that declare a manifest but no engine must not be re-routed."""
    engines = chp._projection_engine_by_harness(PROJECT_ROOT)
    registry, _ = chp.load_registry(PROJECT_ROOT)
    harnesses = registry.get("harnesses") or {}
    manifest_only = [
        name
        for name, cfg in harnesses.items()
        if isinstance(cfg, dict) and cfg.get("skill_adapter_manifest") and name not in engines
    ]
    assert manifest_only, "expected at least one manifest-only harness to pin the API branch"
    for name in manifest_only:
        assert name not in engines


def test_generator_resolves_from_registry_declaration():
    """Resolution comes from the registry so Phase-D cutovers need no map edit."""
    engines = chp._projection_engine_by_harness(PROJECT_ROOT)
    assert PROJECTION_MARKER not in chp.ADAPTER_GENERATOR_BY_MARKER
    assert engines[PROJECTION_HARNESS] == "scripts/harness_projection/project_harness.py"


def test_stub_generator_map_is_unchanged():
    assert set(chp.ADAPTER_GENERATOR_BY_MARKER) == set(STUB_MARKERS)


# --- M4: expected-content oracle ----------------------------------------


def test_projection_oracle_is_the_engine_plan():
    """Expected content is the engine's own output, not a re-implementation."""
    surface = ".goose/skills/gtkb-bridge/SKILL.md"
    if not (PROJECT_ROOT / surface).is_file():
        pytest.skip(f"{surface} is absent in this checkout")
    rendered = chp._render_expected_adapter(
        capability={"id": "skill.bridge", "canonical_name": "gtkb-bridge"},
        adapter_source=".harness-baseline-configuration/skills/gtkb-bridge/SKILL.md",
        surface=surface,
        source_text="",
        source_hash="unused-for-projection-harnesses",
        expected_marker=PROJECTION_MARKER,
        projection_harness=PROJECTION_HARNESS,
    )
    assert rendered is not None
    assert rendered == (PROJECT_ROOT / surface).read_text(encoding="utf-8")


def test_tampered_body_is_detected():
    """The oracle catches body tampering the stub comparison could not see.

    This is the test that shows the gate got stronger rather than looser.
    """
    surface = ".goose/skills/gtkb-bridge/SKILL.md"
    if not (PROJECT_ROOT / surface).is_file():
        pytest.skip(f"{surface} is absent in this checkout")
    expected = chp._render_expected_adapter(
        capability={"id": "skill.bridge", "canonical_name": "gtkb-bridge"},
        adapter_source=".harness-baseline-configuration/skills/gtkb-bridge/SKILL.md",
        surface=surface,
        source_text="",
        source_hash="unused-for-projection-harnesses",
        expected_marker=PROJECTION_MARKER,
        projection_harness=PROJECTION_HARNESS,
    )
    tampered = expected.replace("\n## ", "\n## Injected Section\n\nrogue\n\n## ", 1)
    assert tampered != expected, "fixture must actually differ from the plan"
    assert chp._normalized_adapter_semantics(tampered, PROJECTION_MARKER) != chp._normalized_adapter_semantics(
        expected, PROJECTION_MARKER
    )


def test_unknown_projection_surface_yields_no_expected_content():
    """A surface absent from the plan must not silently render as PASS."""
    assert (
        chp._render_expected_adapter(
            capability={"id": "skill.nope", "canonical_name": "nope"},
            adapter_source=".harness-baseline-configuration/skills/nope/SKILL.md",
            surface=".goose/skills/definitely-not-a-managed-surface/SKILL.md",
            source_text="",
            source_hash="x",
            expected_marker=PROJECTION_MARKER,
            projection_harness=PROJECTION_HARNESS,
        )
        is None
    )


# --- STALE preservation --------------------------------------------------


def test_wrong_digest_is_visible_to_the_hash_comparison():
    """A wrong Canonical source sha256 must remain detectable."""
    right, wrong = "d" * 64, "e" * 64
    text = "# Skill\n\nbody\n\n" + _projection_block(digest=wrong)
    metadata = chp._adapter_metadata(text, PROJECTION_MARKER)
    assert metadata["Canonical source sha256"] != right


def test_missing_block_yields_no_generator_identity():
    """Absent metadata must resolve to no generator, which the checker reports STALE."""
    metadata = chp._adapter_metadata("# Skill\n\nno block here\n", PROJECTION_MARKER)
    assert metadata == {}
    assert metadata.get("Generated by") is None
