from __future__ import annotations

import hashlib
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate_codex_skill_adapters.py"
PARITY_PATH = REPO_ROOT / "scripts" / "check_harness_parity.py"
DOCTOR_PATH = REPO_ROOT / "groundtruth-kb" / "src" / "groundtruth_kb" / "project" / "doctor.py"


def _load_module(name: str, path: Path):
    if str(REPO_ROOT / "groundtruth-kb" / "src") not in sys.path:
        sys.path.insert(0, str(REPO_ROOT / "groundtruth-kb" / "src"))
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _source_hash(text: str) -> str:
    return hashlib.sha256((text.rstrip() + "\n").encode("utf-8")).hexdigest()


def _write_registry(project_root: Path, source_hash: str) -> None:
    registry_path = project_root / "config" / "agent-control" / "harness-capability-registry.toml"
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        f"""
registry_id = "test-registry"
purpose = "test"

[[capabilities]]
id = "skill.review"
kind = "skill"
canonical_name = "review"
canonical_source = ".claude/skills/review/SKILL.md"
required_for_roles = ["loyal-opposition"]
parity_class = "required"

[capabilities.claude]
surface = ".claude/skills/review/SKILL.md"
status = "native"

[capabilities.codex]
surface = ".codex/skills/review/SKILL.md"
status = "adapter"
adapter_source = ".claude/skills/review/SKILL.md"
source_sha256 = "{source_hash}"
""".lstrip(),
        encoding="utf-8",
    )


def _write_canonical_skill(project_root: Path, source_text: str) -> None:
    skill_dir = project_root / ".claude" / "skills" / "review"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_dir.joinpath("SKILL.md").write_text(source_text, encoding="utf-8")


def _write_codex_adapter(project_root: Path, adapter_text: str) -> None:
    adapter_dir = project_root / ".codex" / "skills" / "review"
    adapter_dir.mkdir(parents=True, exist_ok=True)
    adapter_dir.joinpath("SKILL.md").write_text(adapter_text, encoding="utf-8")


def _valid_source() -> str:
    return "---\nname: review\ndescription: Test skill.\n---\n\n# review\n"


def _valid_adapter(source_text: str) -> str:
    source_hash = _source_hash(source_text)
    return "\n".join(
        [
            "---",
            "name: review",
            "description: Test skill.",
            "---",
            "<!-- GTKB-CODEX-SKILL-ADAPTER",
            "Generated: true",
            "Generated by: scripts/generate_codex_skill_adapters.py",
            "Canonical source: .claude/skills/review/SKILL.md",
            f"Canonical source sha256: {source_hash}",
            "Generated at: 2026-06-03T00:00:00Z",
            "Do not edit this adapter directly. Edit the canonical source and regenerate.",
            "GTKB-CODEX-SKILL-ADAPTER -->",
            "",
            "# review",
            "",
        ]
    )


def test_generator_detects_missing_canonical_frontmatter(tmp_path: Path) -> None:
    module = _load_module("generate_codex_skill_adapters_smoke", GENERATOR_PATH)
    source_text = "# review\n\nMissing frontmatter.\n"
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))

    try:
        module.generate(tmp_path, check=True)
    except module.SkillFrontmatterError as exc:
        assert "missing opening YAML frontmatter delimiter" in str(exc)
    else:
        raise AssertionError("generator must fail closed on missing skill frontmatter")


def test_generator_detects_malformed_canonical_frontmatter(tmp_path: Path) -> None:
    module = _load_module("generate_codex_skill_adapters_malformed_smoke", GENERATOR_PATH)
    source_text = "---\nname: review\ndescription Test skill.\n---\n\n# review\n"
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))

    try:
        module.generate(tmp_path, check=True)
    except module.SkillFrontmatterError as exc:
        assert "malformed frontmatter line" in str(exc)
    else:
        raise AssertionError("generator must fail closed on malformed skill frontmatter")


def test_generator_renders_bom_source_frontmatter_first(tmp_path: Path) -> None:
    module = _load_module("generate_codex_skill_adapters_bom_smoke", GENERATOR_PATH)
    source_text = "\ufeff" + _valid_source()
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))

    module.generate(tmp_path)

    adapter = (tmp_path / ".codex" / "skills" / "review" / "SKILL.md").read_text(encoding="utf-8")
    assert adapter.startswith("---\nname: review\n")
    assert "GTKB-CODEX-SKILL-ADAPTER" in adapter


def test_harness_parity_detects_missing_codex_adapter_frontmatter(tmp_path: Path) -> None:
    module = _load_module("check_harness_parity_missing_smoke", PARITY_PATH)
    source_text = _valid_source()
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))
    _write_codex_adapter(tmp_path, "name: review\ndescription: Test skill.\n\n# review\n")

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "FAIL"
    assert report.results[0].state == "MISSING"
    assert "missing opening YAML frontmatter delimiter" in report.results[0].note


def test_harness_parity_detects_malformed_codex_adapter_frontmatter(tmp_path: Path) -> None:
    module = _load_module("check_harness_parity_smoke", PARITY_PATH)
    source_text = _valid_source()
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))
    _write_codex_adapter(
        tmp_path,
        "---\nname: review\ndescription Test skill.\n---\n\n# review\n",
    )

    report = module.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")

    assert report.overall_status == "FAIL"
    assert report.results[0].state == "MISSING"
    assert "not Codex-loadable" in report.results[0].note


def test_doctor_detects_missing_codex_adapter_frontmatter(tmp_path: Path) -> None:
    module = _load_module("doctor_codex_skill_load_smoke", DOCTOR_PATH)
    _write_codex_adapter(tmp_path, "name: review\ndescription: Test skill.\n\n# review\n")

    check = module._check_codex_skill_load_health(tmp_path)

    assert check.status == "fail"
    assert "missing opening YAML frontmatter delimiter" in check.message


def test_doctor_detects_malformed_codex_adapter_frontmatter(tmp_path: Path) -> None:
    module = _load_module("doctor_codex_skill_malformed_smoke", DOCTOR_PATH)
    _write_codex_adapter(tmp_path, "---\nname: review\ndescription Test skill.\n---\n\n# review\n")

    check = module._check_codex_skill_load_health(tmp_path)

    assert check.status == "fail"
    assert "malformed frontmatter line" in check.message


def test_skill_load_smoke_passes_on_valid_codex_adapter(tmp_path: Path) -> None:
    parity = _load_module("check_harness_parity_valid_smoke", PARITY_PATH)
    doctor = _load_module("doctor_codex_skill_valid_smoke", DOCTOR_PATH)
    source_text = _valid_source()
    _write_canonical_skill(tmp_path, source_text)
    _write_registry(tmp_path, _source_hash(source_text))
    _write_codex_adapter(tmp_path, _valid_adapter(source_text))

    report = parity.check_harness_parity(tmp_path, harness="codex", role="loyal-opposition")
    doctor_check = doctor._check_codex_skill_load_health(tmp_path)

    assert report.overall_status == "PASS"
    assert report.results[0].state == "PASS"
    assert doctor_check.status == "pass"
