"""Tests for the WI-4466 ``gt`` CLI availability doctor check.

Per ``bridge/gtkb-wi4466-gt-cli-availability-doctor-check-001.md`` (NEW) and
``-002`` (Codex GO). Covers the GO's required evidence: PATH-present pass,
missing-PATH + canonical in-root venv fallback warning, genuinely-unavailable
fail, dynamic registry discovery, and fallback-path consistency with
``scripts.install_gt_path_shim.resolve_venv_gt_exe``.

(c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import install_gt_path_shim  # noqa: E402
from groundtruth_kb.project.checks import get_registered_checks  # noqa: E402
from groundtruth_kb.project.checks import gt_cli_availability as helper  # noqa: E402


def test_gt_on_path_passes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A non-generated gt resolvable on PATH yields a pass naming the path."""
    fake_path = tmp_path / "onpath" / "gt"
    fake_path.parent.mkdir(parents=True)
    fake_path.write_text("external command", encoding="utf-8")
    fake = str(fake_path)
    monkeypatch.setattr(shutil, "which", lambda name: fake if name == "gt" else None)
    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "pass"
    assert result.found is True
    assert fake in result.message
    assert "structural inspection skipped" in result.message


def test_source_tree_module_fallback_warns(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Not on PATH but venv Python + source tree present -> warning."""
    monkeypatch.setattr(shutil, "which", lambda name: None)
    venv_python = install_gt_path_shim.resolve_venv_python_exe(tmp_path, sys.platform)
    venv_python.parent.mkdir(parents=True, exist_ok=True)
    venv_python.write_text("python", encoding="utf-8")
    source_tree = install_gt_path_shim.resolve_source_tree(tmp_path)
    source_tree.mkdir(parents=True)
    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "warning"
    assert result.found is True
    assert "not on PATH" in result.message
    assert "PYTHONPATH" in result.message


def test_generated_source_tree_shim_passes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Generated WI-4954 shim passes when its venv Python and source tree exist."""
    venv_python = install_gt_path_shim.resolve_venv_python_exe(tmp_path, sys.platform)
    venv_python.parent.mkdir(parents=True, exist_ok=True)
    venv_python.write_text("python", encoding="utf-8")
    source_tree = install_gt_path_shim.resolve_source_tree(tmp_path)
    source_tree.mkdir(parents=True)

    rendered = install_gt_path_shim.render_for_platform(tmp_path, sys.platform)
    shim = tmp_path / "path-bin" / rendered["filename"]
    shim.parent.mkdir()
    shim.write_text(rendered["content"], encoding="utf-8")
    monkeypatch.setattr(shutil, "which", lambda name: str(shim) if name == "gt" else None)

    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "pass"
    assert result.found is True
    assert "source-tree module shim targets are present" in result.message


def test_generated_source_tree_shim_missing_python_fails(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Generated WI-4954 shim fails when its venv Python target is missing."""
    source_tree = install_gt_path_shim.resolve_source_tree(tmp_path)
    source_tree.mkdir(parents=True)
    rendered = install_gt_path_shim.render_for_platform(tmp_path, sys.platform)
    shim = tmp_path / "path-bin" / rendered["filename"]
    shim.parent.mkdir()
    shim.write_text(rendered["content"], encoding="utf-8")
    monkeypatch.setattr(shutil, "which", lambda name: str(shim) if name == "gt" else None)

    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "fail"
    assert result.found is False
    assert "target(s) are missing" in result.message


def test_generated_legacy_stale_gt_exe_shim_fails(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A generated WI-4530 shim pointing at a missing venv gt.exe fails."""
    legacy_gt = install_gt_path_shim.resolve_venv_gt_exe(tmp_path, sys.platform)
    shim = tmp_path / "path-bin" / ("gt.cmd" if sys.platform == "win32" else "gt")
    shim.parent.mkdir()
    if sys.platform == "win32":
        content = (
            "@echo off\n"
            "REM gt CLI launcher shim (WI-4530) -- generated by scripts/install_gt_path_shim.py\n"
            f'"{legacy_gt}" %*\n'
        )
    else:
        content = (
            "#!/usr/bin/env bash\n"
            "# gt CLI launcher shim (WI-4530) -- generated by scripts/install_gt_path_shim.py\n"
            f'exec "{legacy_gt}" "$@"\n'
        )
    shim.write_text(content, encoding="utf-8")
    monkeypatch.setattr(shutil, "which", lambda name: str(shim) if name == "gt" else None)

    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "fail"
    assert result.found is False
    assert "missing legacy venv console script" in result.message


def test_unavailable_fails(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Neither on PATH nor an in-root module fallback -> fail (missing CLI caught)."""
    monkeypatch.setattr(shutil, "which", lambda name: None)
    result = helper.check_gt_cli_availability(tmp_path)
    assert result.status == "fail"
    assert result.found is False
    assert "unavailable" in result.message


def test_check_is_registered() -> None:
    """The check is auto-discovered by the doctor registry (ADR-REGISTRY-DISCOVERY-001)."""
    assert "gt_cli_availability" in get_registered_checks()


def test_fallback_path_matches_shim_generator(tmp_path: Path) -> None:
    """The check's fallback paths equal the WI-4954 generator paths (no drift)."""
    assert helper._venv_python_path(tmp_path, sys.platform) == install_gt_path_shim.resolve_venv_python_exe(
        tmp_path, sys.platform
    )
    assert helper._source_tree_path(tmp_path) == install_gt_path_shim.resolve_source_tree(tmp_path)


def test_check_is_advisory_required_false(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The check is required=False (developer-environment quality, not a hard gate)."""
    monkeypatch.setattr(shutil, "which", lambda name: None)
    result = helper.check_gt_cli_availability(tmp_path)
    assert result.required is False
    assert result.name
