"""Platform tests for WI-4512: the GTKB-DbSnapshot launcher must be in-root.

The scheduled-task launcher generated by ``scripts/install_db_snapshot_task.ps1``
is an active runtime dependency (the daily task executes it). It must live under
the GT-KB project root and survive Temp-cleaning, not under ``$env:TEMP``. The
snapshot OUTPUT path (``%LOCALAPPDATA%\\gtkb-snapshots``) is governed by the
separate DB-Snapshot Output Exception and is unchanged by this fix.

Specification Links:
- GOV-STANDING-BACKLOG-001 (WI-4512, P3 git-tooling durability defect)
- ADR-ISOLATION-APPLICATION-PLACEMENT-001
- .claude/rules/project-root-boundary.md (project-root boundary; the launcher is
  an out-of-root active dependency that must be in-root)
- DELIB-2026-06-13-RELIABILITY-STANDALONE-DEFECT-BATCH-2-ADMISSION
"""

from __future__ import annotations

import re
from pathlib import Path


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _installer_text() -> str:
    installer = _project_root() / "scripts" / "install_db_snapshot_task.ps1"
    assert installer.exists(), f"installer not found: {installer}"
    return installer.read_text(encoding="utf-8")


def _installer_code() -> str:
    """Installer text with PowerShell comments stripped.

    Block comments (``<# ... #>``) and whole-line ``#`` comments are removed so
    static assertions target executable code, not prose that may legitimately
    *mention* a forbidden pattern (e.g. an explanatory note about ``$env:TEMP``).
    """
    text = _installer_text()
    text = re.sub(r"<#.*?#>", "", text, flags=re.DOTALL)
    lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("#")]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Launcher path is in-root, not %TEMP%
# ---------------------------------------------------------------------------


def test_launcher_path_is_in_root_not_temp() -> None:
    """The launcher must not be written to ``$env:TEMP`` and must be in-root."""
    code = _installer_code()

    # No $env:TEMP launcher path anywhere in the installer code.
    assert "$env:TEMP" not in code, (
        "Installer must not place the scheduled-task launcher under $env:TEMP (WI-4512: out-of-root active dependency)."
    )

    # The launcher is built from the in-root project root.
    assert re.search(
        r"Join-Path\s+\$ProjectRoot\s+[\"']\.gtkb-state",
        code,
    ), "Launcher path must be an in-root path joined from $ProjectRoot."


# ---------------------------------------------------------------------------
# Scheduled-task argument references the in-root launcher
# ---------------------------------------------------------------------------


def test_scheduled_task_argument_is_in_root() -> None:
    """The scheduled-task -Argument must point at the in-root launcher var."""
    code = _installer_code()

    # The -Argument line must reference the launcher variable, not a temp path.
    arg_match = re.search(r"-Argument\s+(\S+)", code)
    assert arg_match, "Could not find -Argument in installer."
    arg = arg_match.group(1)
    assert "launcherScript" in arg, f"-Argument must reference the in-root launcher variable, got: {arg!r}"
    assert "tempScript" not in arg and "TEMP" not in arg, (
        f"-Argument must not reference a temp launcher path, got: {arg!r}"
    )


# ---------------------------------------------------------------------------
# Parent directory is ensured before write
# ---------------------------------------------------------------------------


def test_installer_ensures_launcher_dir() -> None:
    """The installer must create the launcher parent dir before Set-Content."""
    code = _installer_code()

    new_item_idx = code.find("New-Item -ItemType Directory -Force")
    assert new_item_idx != -1, (
        "Installer must create the launcher parent directory "
        "(New-Item -ItemType Directory -Force) before writing the launcher."
    )

    set_content_idx = code.find("Set-Content -Path $launcherScript")
    assert set_content_idx != -1, "Installer must write the launcher via Set-Content -Path $launcherScript."

    assert new_item_idx < set_content_idx, "Parent-directory creation must precede the Set-Content launcher write."


def test_scheduled_task_prefers_pythonw_and_is_hidden() -> None:
    """The registered task must use a GUI-subsystem Python and hidden settings."""
    code = _installer_code()

    assert "pythonw.exe" in code, "Scheduled task launcher must prefer pythonw.exe to avoid console allocation."
    assert re.search(
        r"Join-Path\s+\$ProjectRoot\s+[\"']groundtruth-kb\\\.venv\\Scripts\\pythonw\.exe[\"']",
        code,
    ), "Installer must prefer the project venv pythonw.exe before PATH fallback."
    assert re.search(
        r"New-ScheduledTaskSettingsSet[\s\S]*-Hidden[\s\S]*-ExecutionTimeLimit",
        code,
    ), "Scheduled task settings must include -Hidden."


def test_pythonw_launcher_writes_last_run_file_instead_of_stdout() -> None:
    """A pythonw.exe task must not depend on an attached stdout console."""
    code = _installer_code()

    assert "print(" not in code
    assert "last-run.json" in code
    assert "result_path.write_text" in code
