# © 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""
GroundTruth KB — D2 Azure ADR Verification Harness.

Verifies whether each of the 13 Azure instance-ADR skeletons generated by
``scaffold_adrs()`` has been answered by the adopter-owner.

Per Codex GO binding condition F4 from bridge/gtkb-azure-adr-template-activation-002.md:
an ADR is `answered` ONLY when:

1. It exists in the KB.
2. Its description contains all 9 taxonomy-§5.1 section headings.
3. The Decision, Rationale, and Rejected alternatives sections each contain
   non-empty, non-placeholder content.

Malformed cases (placeholder removed but section empty or missing) remain
`unanswered`, not `answered`.

Copyright (c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
Licensed under AGPL-3.0-or-later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from groundtruth_kb.db import KnowledgeDB

from groundtruth_kb._azure_adr_instance_templates import (
    ADR_MANDATORY_OWNER_ANSWER_HEADINGS,
    ADR_PLACEHOLDER,
    ADR_REQUIRED_HEADINGS,
    AZURE_ADR_INSTANCE_IDS,
)

AdrStatus = Literal["missing", "unanswered", "answered"]


@dataclass(frozen=True)
class AdrVerificationEntry:
    """Per-ADR verification result.

    Attributes:
        adr_id: The ADR ID (e.g., ``ADR-AZURE-LANDING-ZONE-001``).
        status: ``'missing'`` | ``'unanswered'`` | ``'answered'``.
        missing_headings: Section headings from ``ADR_REQUIRED_HEADINGS``
            that were NOT found in the description. Empty when status is
            ``answered``.
        unanswered_sections: Mandatory-answer section headings (from
            ``ADR_MANDATORY_OWNER_ANSWER_HEADINGS``) whose content is empty
            or still contains the placeholder token. Empty when status is
            ``answered``.
        spec_status: The current ``status`` field of the spec row, or
            ``None`` if missing. Reported for context only — does NOT gate
            the `answered` classification (per Codex F5: status promotion
            is not required).
    """

    adr_id: str
    status: AdrStatus
    missing_headings: tuple[str, ...] = ()
    unanswered_sections: tuple[str, ...] = ()
    spec_status: str | None = None


@dataclass(frozen=True)
class AdrVerificationReport:
    """Summary of a verify_azure_adrs() call."""

    entries: list[AdrVerificationEntry] = field(default_factory=list)
    total: int = 0
    answered_count: int = 0
    unanswered_count: int = 0
    missing_count: int = 0

    def all_answered(self) -> bool:
        """True iff every ADR is answered (suitable for CI exit-0 gating)."""
        return self.missing_count == 0 and self.unanswered_count == 0 and self.total > 0


# ---------------------------------------------------------------------------
# Section parsing
# ---------------------------------------------------------------------------


def _extract_section(description: str, heading: str) -> str | None:
    """Return the text of the ``## {heading}`` section, or None if heading missing.

    Section content is defined as everything between the heading LINE and the
    next ``## `` heading line (or end of document). An empty body returns
    an empty string. Returned content is stripped of leading/trailing
    whitespace.
    """
    # Require the match to be followed by newline (or end-of-document) so that
    # ``## Decision`` does not accidentally match ``## Decision scope``.
    marker = f"## {heading}"
    idx = -1
    search_from = 0
    while True:
        candidate = description.find(marker, search_from)
        if candidate < 0:
            break
        end = candidate + len(marker)
        # Match only if next char is newline or EOF.
        if end == len(description) or description[end] == "\n":
            idx = candidate
            break
        search_from = end
    if idx < 0:
        return None
    # Advance to end of heading line (handles heading-is-last-line case).
    eol = description.find("\n", idx)
    if eol < 0:
        return ""
    after_heading = description[eol + 1 :]
    # If the next non-empty line is itself another ``## `` heading, the body
    # is empty (next section immediately follows).
    stripped_prefix = after_heading.lstrip("\n")
    if stripped_prefix.startswith("## "):
        return ""
    # Otherwise find the next ``\n## `` (start of next section).
    next_idx = after_heading.find("\n## ")
    body = after_heading if next_idx < 0 else after_heading[:next_idx]
    return body.strip()


def _is_answered_section(body: str | None) -> bool:
    """A mandatory section is `answered` iff non-empty AND does not contain placeholder."""
    if body is None:
        return False
    if not body.strip():
        return False
    return ADR_PLACEHOLDER not in body


# ---------------------------------------------------------------------------
# Public harness entry point
# ---------------------------------------------------------------------------


def verify_azure_adrs(db: KnowledgeDB) -> AdrVerificationReport:
    """Verify that each of the 13 Azure instance ADRs exists and has been answered.

    An ADR is classified `answered` ONLY when:
    1. The spec exists in the KB.
    2. All 9 taxonomy §5.1 section headings are present in the description.
    3. Decision, Rationale, and Rejected alternatives sections each have
       non-empty, non-placeholder content.

    Any other state is `unanswered` (if spec exists but sections fail) or
    `missing` (if spec does not exist).
    """
    entries: list[AdrVerificationEntry] = []
    answered_count = 0
    unanswered_count = 0
    missing_count = 0

    for adr_id in AZURE_ADR_INSTANCE_IDS:
        spec = db.get_spec(adr_id)
        if spec is None:
            entries.append(
                AdrVerificationEntry(
                    adr_id=adr_id,
                    status="missing",
                )
            )
            missing_count += 1
            continue

        description = spec.get("description") or ""
        spec_status = spec.get("status")

        # Check all 9 required headings are present.
        # Use the same heading-boundary semantics as ``_extract_section`` so
        # ``## Decision`` does not match ``## Decision scope`` or vice-versa.
        missing_headings: list[str] = []
        for heading in ADR_REQUIRED_HEADINGS:
            if _extract_section(description, heading) is None:
                missing_headings.append(heading)

        # Check mandatory owner-answer sections have substantive content.
        unanswered_sections: list[str] = []
        for heading in ADR_MANDATORY_OWNER_ANSWER_HEADINGS:
            body = _extract_section(description, heading)
            if not _is_answered_section(body):
                unanswered_sections.append(heading)

        if not missing_headings and not unanswered_sections:
            status: AdrStatus = "answered"
            answered_count += 1
        else:
            status = "unanswered"
            unanswered_count += 1

        entries.append(
            AdrVerificationEntry(
                adr_id=adr_id,
                status=status,
                missing_headings=tuple(missing_headings),
                unanswered_sections=tuple(unanswered_sections),
                spec_status=spec_status,
            )
        )

    return AdrVerificationReport(
        entries=entries,
        total=len(AZURE_ADR_INSTANCE_IDS),
        answered_count=answered_count,
        unanswered_count=unanswered_count,
        missing_count=missing_count,
    )
