# © 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""
GroundTruth KB — D2 Azure ADR Instance Scaffold.

Generates 13 instance-ADR skeletons via ``gt scaffold adrs --profile azure-enterprise``.
Paired with D1's ADR template spec; each skeleton references a D1 category spec
and carries the 9-section template body from taxonomy §5.1.

Authoritative source: bridge/gtkb-azure-adr-template-activation-002.md GO.

Copyright (c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
Licensed under AGPL-3.0-or-later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from groundtruth_kb.db import KnowledgeDB


# ---------------------------------------------------------------------------
# Config + report dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AdrScaffoldConfig:
    """Configuration for an ADR scaffold run.

    Attributes:
        profile: Currently only 'azure-enterprise' is supported. Future
            readiness profiles may add their own ADR template sets.
        changed_by: Author attribution for ``insert_spec`` calls.
        change_reason: Change reason for ``insert_spec`` calls.
    """

    profile: str = "azure-enterprise"
    changed_by: str = "adr-scaffold-generator"
    change_reason: str = "Generated by D2 ADR scaffold (gtkb-azure-adr-template-activation)"


@dataclass(frozen=True)
class AdrScaffoldReport:
    """Output of a scaffold_adrs() call.

    Attributes:
        generated: List of generated ADR spec dicts. In dry-run mode these
            are synthetic template dicts; in apply mode they are the
            freshly-inserted specs from db.
        skipped: List of {id, handle, reason} for ADRs skipped because a
            spec with the same handle already exists.
        dry_run: True when the report came from a dry run (nothing written
            to the database).
    """

    generated: list[dict[str, Any]] = field(default_factory=list)
    skipped: list[dict[str, Any]] = field(default_factory=list)
    dry_run: bool = True


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def scaffold_adrs(
    db: KnowledgeDB,
    config: AdrScaffoldConfig,
    *,
    dry_run: bool = True,
) -> AdrScaffoldReport:
    """Generate 13 instance-ADR skeletons for the given profile.

    By default (``dry_run=True``) nothing is written to the database —
    the return value is an AdrScaffoldReport showing what WOULD be generated.

    When ``dry_run=False``, each generated ADR is inserted into the database
    with ``authority='inferred'`` and ``type='architecture_decision'`` so the
    adopter-owner can later replace the ``<<ADOPTER-ANSWER-REQUIRED>>``
    placeholders in the Decision, Rationale, and Rejected alternatives
    sections, then promote ``status`` to ``'implemented'`` via
    ``db.update_spec(...)``.

    Pre-existing ADRs (matched by ``handle``) are skipped, not overwritten.
    """
    if config.profile != "azure-enterprise":
        raise ValueError(f"Unsupported profile {config.profile!r}. Only 'azure-enterprise' is supported at D2.")

    # Local import to avoid touching module import graph if only the type is
    # referenced (keeps _azure_adr_instance_templates optional for non-azure
    # callers).
    from groundtruth_kb._azure_adr_instance_templates import (
        azure_adr_instance_templates,
    )

    generated: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []

    for adr_data in azure_adr_instance_templates():
        handle = adr_data.get("handle")

        # Skip if a spec with this handle already exists.
        if handle:
            existing = db.list_specs(handle=handle)
            if existing:
                skipped.append(
                    {
                        "id": adr_data["id"],
                        "handle": handle,
                        "reason": f"Spec with handle {handle!r} already exists",
                    }
                )
                continue

        if dry_run:
            generated.append({**adr_data})
        else:
            insert_kwargs: dict[str, Any] = {
                "id": adr_data["id"],
                "title": adr_data["title"],
                "status": adr_data.get("status", "specified"),
                "changed_by": config.changed_by,
                "change_reason": config.change_reason,
                "description": adr_data.get("description"),
                "section": adr_data.get("section"),
                "scope": adr_data.get("scope"),
                "handle": adr_data.get("handle"),
                "tags": adr_data.get("tags"),
                "assertions": adr_data.get("assertions"),
                "type": adr_data.get("type", "architecture_decision"),
                "authority": "inferred",
                "testability": adr_data.get("testability"),
            }
            created = db.insert_spec(**insert_kwargs)
            assert created is not None, "insert_spec returned None after successful insert"
            stored = db.get_spec(created["id"])
            generated.append(dict(stored) if stored is not None else {**adr_data})

    return AdrScaffoldReport(
        generated=generated,
        skipped=skipped,
        dry_run=dry_run,
    )
