# © 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""
GroundTruth KB — F6 Specification Scaffold Generator.

Generates a starter set of governance, infrastructure, AI-component, and
compliance specifications for a newly-scaffolded project. Produces either
a dry-run report (default) or commits specs to the KB with
``authority='inferred'`` so owners can review and promote to
``authority='stated'`` via ``db.update_spec()``.

Used by ``gt project init`` (optional via ``ScaffoldOptions.spec_scaffold``)
and by the standalone ``gt scaffold specs`` CLI command.

Phase A: governance + infrastructure templates (minimal profile).
Phase B: adds ai_components + compliance templates (full profile).

Copyright (c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
Licensed under AGPL-3.0-or-later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from groundtruth_kb.db import KnowledgeDB


# ---------------------------------------------------------------------------
# Config + report dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SpecScaffoldConfig:
    """Configuration for a spec scaffold run.

    Attributes:
        profile: Scaffold profile — 'minimal' (governance + infra) or
            'full' (adds ai_components + compliance).
        include_governance: Include governance templates (default True).
        include_infra: Include infrastructure templates (default True).
        include_ai_components: Include AI component templates
            (default: True when profile='full', False when 'minimal').
        include_compliance: Include compliance templates
            (default: True when profile='full', False when 'minimal').
        changed_by: Author attribution for ``insert_spec`` calls.
        change_reason: Change reason for ``insert_spec`` calls.
    """

    profile: str = "minimal"
    include_governance: bool = True
    include_infra: bool = True
    include_ai_components: bool | None = None
    include_compliance: bool | None = None
    changed_by: str = "scaffold-generator"
    change_reason: str = "Generated by F6 spec scaffold"

    def resolve_phases(self) -> dict[str, bool]:
        """Resolve effective phase inclusion based on profile + overrides."""
        full = self.profile == "full"
        return {
            "governance": self.include_governance,
            "infra": self.include_infra,
            "ai_components": (self.include_ai_components if self.include_ai_components is not None else full),
            "compliance": (self.include_compliance if self.include_compliance is not None else full),
        }


@dataclass(frozen=True)
class ScaffoldReport:
    """Output of a scaffold_specs() call.

    Attributes:
        generated: List of generated spec dicts (each includes a 'quality' key
            when quality scoring ran). In dry_run mode these are synthetic;
            in apply mode these are the freshly-inserted specs from db.
        skipped: List of {id, reason} for specs skipped due to pre-existing
            handles or other conflicts.
        quality_summary: Count of generated specs in each quality tier.
        low_quality_warnings: List of {id, tier, score} for specs scoring
            bronze or needs-work — surface to the owner during review.
        dry_run: True when the report came from a dry run (nothing written
            to the database).
    """

    generated: list[dict] = field(default_factory=list)
    skipped: list[dict] = field(default_factory=list)
    quality_summary: dict[str, int] = field(default_factory=dict)
    low_quality_warnings: list[dict] = field(default_factory=list)
    dry_run: bool = True


# ---------------------------------------------------------------------------
# Template catalog
# ---------------------------------------------------------------------------


def _governance_templates() -> list[dict[str, Any]]:
    """Governance specs: test discipline, documentation freshness, review gates."""
    return [
        {
            "id": "GOV-SCAFFOLD-01",
            "title": "Every feature spec must have at least one test",
            "type": "governance",
            "status": "specified",
            "section": "governance",
            "scope": "testing",
            "handle": "test-discipline",
            "description": (
                "Every specification of type 'requirement' must have at least "
                "one linked test before being promoted past status 'specified'."
            ),
            "assertions": [
                {
                    "type": "count",
                    "file": "tests/**/*.py",
                    "pattern": "def test_",
                    "operator": ">=",
                    "value": 1,
                }
            ],
            "testability": "automatable",
        },
        {
            "id": "GOV-SCAFFOLD-02",
            "title": "README exists and is non-empty",
            "type": "governance",
            "status": "specified",
            "section": "governance",
            "scope": "documentation",
            "handle": "readme-exists",
            "description": "A project README must exist at the repository root.",
            "assertions": [{"type": "file_exists", "file": "README.md"}],
            "testability": "automatable",
        },
    ]


def _infra_templates() -> list[dict[str, Any]]:
    """Infrastructure specs: CI config, secret hygiene."""
    return [
        {
            "id": "INFRA-SCAFFOLD-01",
            "title": "CI workflow configuration exists",
            "type": "requirement",
            "status": "specified",
            "section": "infrastructure",
            "scope": "ci",
            "handle": "ci-config",
            "description": "At least one CI workflow definition must exist.",
            "assertions": [{"type": "glob", "pattern": ".github/workflows/*.yml"}],
            "testability": "automatable",
        },
        {
            "id": "INFRA-SCAFFOLD-02",
            "title": "No committed AWS access keys",
            "type": "requirement",
            "status": "specified",
            "section": "infrastructure",
            "scope": "secrets",
            "handle": "no-aws-keys",
            "description": (
                "Source tree must not contain hard-coded AWS access keys. "
                "Pattern matches the AKIA[0-9A-Z]{16} access-key-id format."
            ),
            "assertions": [
                {
                    "type": "grep_absent",
                    "file": "src/**/*.py",
                    "pattern": r"AKIA[0-9A-Z]{16}",
                }
            ],
            "testability": "automatable",
        },
    ]


def _ai_component_templates() -> list[dict[str, Any]]:
    """AI component specs (full profile only)."""
    return [
        {
            "id": "AI-SCAFFOLD-01",
            "title": "AI model inventory documented",
            "type": "requirement",
            "status": "specified",
            "section": "ai_components",
            "scope": "inventory",
            "handle": "ai-model-inventory",
            "description": (
                "An inventory of AI/ML models used by this project must be "
                "documented in docs/ai-inventory.md or equivalent."
            ),
            "assertions": [{"type": "file_exists", "file": "docs/ai-inventory.md"}],
            "testability": "automatable",
        },
    ]


def _compliance_templates() -> list[dict[str, Any]]:
    """Compliance specs (full profile only)."""
    return [
        {
            "id": "COMP-SCAFFOLD-01",
            "title": "Privacy policy document exists",
            "type": "requirement",
            "status": "specified",
            "section": "compliance",
            "scope": "privacy",
            "handle": "privacy-policy",
            "description": "A privacy policy document must exist in the repository.",
            "assertions": [{"type": "file_exists", "file": "PRIVACY.md"}],
            "testability": "automatable",
        },
    ]


_PHASE_TEMPLATE_BUILDERS = {
    "governance": _governance_templates,
    "infra": _infra_templates,
    "ai_components": _ai_component_templates,
    "compliance": _compliance_templates,
}


def _generate_spec_data(config: SpecScaffoldConfig) -> list[dict[str, Any]]:
    """Materialize the list of spec data dicts to generate, per config."""
    phases = config.resolve_phases()
    specs: list[dict[str, Any]] = []
    for phase, enabled in phases.items():
        if not enabled:
            continue
        builder = _PHASE_TEMPLATE_BUILDERS.get(phase)
        if builder is None:
            continue
        specs.extend(builder())
    return specs


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def scaffold_specs(
    db: KnowledgeDB,
    config: SpecScaffoldConfig,
    *,
    dry_run: bool = True,
) -> ScaffoldReport:
    """Generate a starter set of specifications for the given project config.

    By default (``dry_run=True``) nothing is written to the database —
    the return value is a ScaffoldReport showing what WOULD be generated,
    including per-spec quality scores computed via ``db.score_spec_quality()``.

    When ``dry_run=False``, each generated spec is inserted into the database
    with ``authority='inferred'`` so an owner can later promote the spec to
    ``authority='stated'`` via ``db.update_spec(...)``.

    Pre-existing specs (matched by ``handle``) are skipped, not overwritten.
    """
    generated: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    quality_summary: dict[str, int] = {
        "gold": 0,
        "silver": 0,
        "bronze": 0,
        "needs-work": 0,
    }
    low_quality_warnings: list[dict[str, Any]] = []

    for spec_data in _generate_spec_data(config):
        handle = spec_data.get("handle")

        # Skip if a spec with this handle already exists.
        if handle:
            existing = db.list_specs(handle=handle)
            if existing:
                skipped.append(
                    {
                        "id": spec_data["id"],
                        "handle": handle,
                        "reason": f"Spec with handle {handle!r} already exists",
                    }
                )
                continue

        if dry_run:
            # Build a synthetic dict shape that ``score_spec_quality()``
            # understands. The scorer reads assertions from either
            # ``assertions_parsed`` or ``_assertions_parsed`` (see db.py:1086)
            # — populate BOTH so a dry-run spec with executable assertions
            # does not falsely trip the ``NO_ASSERTIONS`` flag.
            synthetic = {
                **spec_data,
                "version": 1,
                "assertions_parsed": spec_data.get("assertions") or [],
                "_assertions_parsed": spec_data.get("assertions") or [],
            }
            quality = db.score_spec_quality(synthetic)
            entry = {**spec_data, "quality": quality}
        else:
            # Apply mode: insert into DB with authority='inferred'.
            insert_kwargs: dict[str, Any] = {
                "id": spec_data["id"],
                "title": spec_data["title"],
                "status": spec_data.get("status", "specified"),
                "changed_by": config.changed_by,
                "change_reason": config.change_reason,
                "description": spec_data.get("description"),
                "section": spec_data.get("section"),
                "scope": spec_data.get("scope"),
                "handle": spec_data.get("handle"),
                "tags": spec_data.get("tags"),
                "assertions": spec_data.get("assertions"),
                "type": spec_data.get("type", "requirement"),
                "authority": "inferred",
                "testability": spec_data.get("testability"),
            }
            created = db.insert_spec(**insert_kwargs)
            # After insert, the spec dict from get_spec() has real parsed
            # fields — score directly off that.
            stored = db.get_spec(created["id"])
            quality = db.score_spec_quality(stored) if stored is not None else {}
            entry = {**(stored or spec_data), "quality": quality}

        tier = quality.get("tier", "needs-work")
        quality_summary[tier] = quality_summary.get(tier, 0) + 1
        if tier in ("bronze", "needs-work"):
            low_quality_warnings.append(
                {
                    "id": spec_data["id"],
                    "tier": tier,
                    "score": quality.get("overall"),
                }
            )
        generated.append(entry)

    return ScaffoldReport(
        generated=generated,
        skipped=skipped,
        quality_summary=quality_summary,
        low_quality_warnings=low_quality_warnings,
        dry_run=dry_run,
    )
