// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'Billing',
      items: [{type: 'autogenerated', dirName: 'billing'}],
    },
  ],
};

export default sidebars;
