"""
Fail-closed Critic/Supervisor safety enforcement.

Implements Decision #16 (Option B+ fail-closed Critic) and Work Item #50.
Guarantees that the AI response pipeline NEVER delivers a response to a
customer that has not been validated by the Critic/Supervisor agent.

Design invariant:
    If the Critic is unreachable, timed out, or returns an error,
    the response is BLOCKED — never delivered to the customer.

    This is a fail-CLOSED policy: the safe default is to withhold the
    response, not to deliver it. The pipeline treats Critic unavailability
    the same as Critic rejection.

Fail-closed behavior:
    ┌─────────────┐     ┌──────────────────┐     ┌──────────────┐
    │  Response    │────>│  CriticPolicy    │────>│  Deliver to  │
    │  Generator   │     │  (this module)   │     │  Customer    │
    └─────────────┘     └──────────────────┘     └──────────────┘
                               │
                          fail-closed gate:
                          - Critic approves → deliver
                          - Critic rejects  → block + log
                          - Critic timeout  → block + log
                          - Critic error    → block + log
                          - Critic down     → block + escalate

Pipeline integration:
    Every response generated by the Response Generator agent must pass
    through CriticPolicy.validate_response() before being returned to
    the customer. The require_critic_approval() wrapper enforces this
    at the pipeline level.

Architecture references:
    - Decision #16: Option B+ with fail-closed Critic (min=2 replicas)
    - Decision #15: Timeout budget — Critic allocation: 800ms
    - Decision #23: Safety guardrails immutable (platform base + Critic)
    - Decision #31: Critic validates all outputs (including fine-tuned)
    - ConversationDocument.critic_passed field (cosmos_schema.py)
    - AuditEventType.SECURITY_EVENT for blocked responses
    - AuditEventType.ESCALATION_TRIGGERED for Critic-unavailable escalation

© 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

import httpx

from src.multi_tenant.cosmos_schema import AuditEventType

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Critic timeout budget (Decision #15 — 800ms of the 8s pipeline deadline)
CRITIC_TIMEOUT_MS = 800

# HTTP timeout for Critic requests (slightly above the budget to allow
# for network overhead — the Critic agent itself has an internal 800ms
# deadline, but we give the HTTP call a small buffer).
CRITIC_HTTP_TIMEOUT_SECONDS = 1.0

# Circuit breaker thresholds (Decision #15 — 3 failures / 15s for Cosmos,
# adapted: 5 failures / 30s for Critic as it has 2 replicas with failover).
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_WINDOW_SECONDS = 30
CIRCUIT_BREAKER_RECOVERY_SECONDS = 15

# Critic endpoint paths (relative to base URL)
CRITIC_VALIDATE_PATH = "/validate"
CRITIC_HEALTH_PATH = "/health"

# Safe fallback message when Critic is unavailable.
# This is the ONLY response the pipeline can deliver without Critic approval.
SAFE_FALLBACK_MESSAGE = (
    "I'm sorry, but I'm unable to respond right now. "
    "Please try again in a moment, or contact our support team for help."
)

# Maximum number of Critic replicas to attempt before giving up.
MAX_REPLICA_ATTEMPTS = 2


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class CriticVerdict(str, Enum):
    """Critic's validation verdict for a response."""

    APPROVED = "approved"
    REJECTED = "rejected"
    MODIFIED = "modified"  # Approved with modifications


class CriticBlockReason(str, Enum):
    """Why a response was blocked by the fail-closed policy."""

    REJECTED = "rejected"                    # Critic rejected the response
    TIMEOUT = "timeout"                      # Critic timed out (800ms)
    ERROR = "error"                          # Critic returned an error
    UNAVAILABLE = "unavailable"              # All Critic replicas down
    CIRCUIT_OPEN = "circuit_open"            # Circuit breaker tripped


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CriticResult:
    """Result of Critic validation for a single response.

    Returned by CriticPolicy.validate_response(). The caller uses
    this to decide whether to deliver the response.

    For the response explainability framework (Decision #28+), this
    result is stored as part of the per-response decision trace.
    """

    approved: bool
    verdict: CriticVerdict | None
    block_reason: CriticBlockReason | None

    # Safety flags raised by the Critic (e.g., "potential_hallucination",
    # "brand_safety_risk", "pii_detected", "jailbreak_attempt")
    flags: list[str]

    # If verdict is MODIFIED, this contains the Critic's revised response
    modified_response: str | None

    # Performance
    latency_ms: float

    # Tracing
    critic_instance: str  # Which Critic replica handled this
    request_id: str       # Correlation ID for this validation


@dataclass(frozen=True)
class CriticHealthStatus:
    """Health status of the Critic/Supervisor agent cluster."""

    healthy: bool
    replicas_available: int
    replicas_total: int
    circuit_breaker_open: bool
    last_check_at: str
    details: dict[str, bool]  # {replica_url: is_healthy}


# ---------------------------------------------------------------------------
# Circuit breaker
# ---------------------------------------------------------------------------


class CircuitBreaker:
    """Simple circuit breaker for Critic availability.

    State machine:
        CLOSED  → (failures >= threshold within window) → OPEN
        OPEN    → (recovery_seconds elapsed)            → HALF_OPEN
        HALF_OPEN → (next call succeeds)                → CLOSED
        HALF_OPEN → (next call fails)                   → OPEN

    When OPEN, all calls are immediately rejected without attempting
    the Critic — this prevents cascading failures and reduces latency
    for the end user (they get the fallback message faster).
    """

    class State(str, Enum):
        CLOSED = "closed"
        OPEN = "open"
        HALF_OPEN = "half_open"

    def __init__(
        self,
        failure_threshold: int = CIRCUIT_BREAKER_FAILURE_THRESHOLD,
        window_seconds: float = CIRCUIT_BREAKER_WINDOW_SECONDS,
        recovery_seconds: float = CIRCUIT_BREAKER_RECOVERY_SECONDS,
    ) -> None:
        self._failure_threshold = failure_threshold
        self._window_seconds = window_seconds
        self._recovery_seconds = recovery_seconds
        self._state = self.State.CLOSED
        self._failures: list[float] = []  # timestamps of recent failures
        self._opened_at: float | None = None

    @property
    def state(self) -> State:
        """Current circuit breaker state."""
        if self._state == self.State.OPEN:
            # Check if recovery period has elapsed
            if (
                self._opened_at is not None
                and time.monotonic() - self._opened_at >= self._recovery_seconds
            ):
                self._state = self.State.HALF_OPEN
        return self._state

    @property
    def is_open(self) -> bool:
        """Whether calls should be rejected (circuit is OPEN)."""
        return self.state == self.State.OPEN

    def record_success(self) -> None:
        """Record a successful call — close the circuit."""
        self._state = self.State.CLOSED
        self._failures.clear()
        self._opened_at = None

    def record_failure(self) -> None:
        """Record a failed call — potentially open the circuit."""
        now = time.monotonic()
        self._failures.append(now)

        # Prune old failures outside the window
        cutoff = now - self._window_seconds
        self._failures = [t for t in self._failures if t > cutoff]

        if len(self._failures) >= self._failure_threshold:
            self._state = self.State.OPEN
            self._opened_at = now
            logger.warning(
                "Critic circuit breaker OPENED: %d failures in %.0fs window",
                len(self._failures), self._window_seconds,
            )

    def reset(self) -> None:
        """Force-reset the circuit breaker to CLOSED."""
        self._state = self.State.CLOSED
        self._failures.clear()
        self._opened_at = None


# ---------------------------------------------------------------------------
# CriticPolicy — fail-closed enforcement
# ---------------------------------------------------------------------------


class CriticPolicy:
    """Fail-closed safety enforcement for the AI response pipeline.

    This is the single enforcement point ensuring no AI response reaches
    a customer without Critic/Supervisor validation. Every response
    generated by the Response Generator must pass through
    validate_response() before delivery.

    The policy is fail-CLOSED: if the Critic cannot be reached, times
    out, or returns an error, the response is blocked. The only response
    that can be delivered without Critic approval is the hardcoded
    SAFE_FALLBACK_MESSAGE.

    Dependencies:
        - Critic/Supervisor agent HTTP endpoints (from AGNTCY upstream)
        - ConversationRepository (to update critic_passed field)
        - AuditLogRepository (to log SECURITY_EVENT on blocks)

    Usage:
        policy = CriticPolicy(
            critic_urls=["http://10.0.1.7:8080", "http://10.0.1.7b:8080"],
            conversation_repo=conversation_repo,
            audit_repo=audit_repo,
        )

        result = await policy.validate_response(
            tenant_id="t-123",
            conversation_id="c-456",
            response_text="Here's our return policy...",
            customer_message="What's your return policy?",
        )

        if result.approved:
            # Safe to deliver (use modified_response if verdict is MODIFIED)
            text = result.modified_response or original_response
            deliver_to_customer(text)
        else:
            deliver_to_customer(SAFE_FALLBACK_MESSAGE)
    """

    def __init__(
        self,
        critic_urls: list[str],
        conversation_repo: Any | None = None,
        audit_repo: Any | None = None,
    ) -> None:
        """Initialize the Critic policy.

        Args:
            critic_urls: HTTP base URLs for Critic/Supervisor replicas.
                Decision #16 requires min=2 replicas, so this list
                should have at least 2 entries.
            conversation_repo: ConversationRepository instance (optional —
                if provided, updates critic_passed field on conversations).
            audit_repo: AuditLogRepository instance (optional — if
                provided, logs SECURITY_EVENT audit entries on blocks).
        """
        if not critic_urls:
            raise ValueError(
                "At least one Critic/Supervisor URL is required. "
                "Decision #16 requires min=2 replicas."
            )

        self._critic_urls = critic_urls
        self._conversations = conversation_repo
        self._audit = audit_repo
        self._circuit_breaker = CircuitBreaker()

        # Shared async HTTP client with connection pooling
        self._http_client: httpx.AsyncClient | None = None

    async def _get_http_client(self) -> httpx.AsyncClient:
        """Lazy-initialize the shared HTTP client."""
        if self._http_client is None or self._http_client.is_closed:
            self._http_client = httpx.AsyncClient(
                timeout=httpx.Timeout(
                    connect=0.5,
                    read=CRITIC_HTTP_TIMEOUT_SECONDS,
                    write=0.5,
                    pool=0.5,
                ),
                limits=httpx.Limits(
                    max_connections=20,
                    max_keepalive_connections=10,
                ),
            )
        return self._http_client

    async def close(self) -> None:
        """Close the HTTP client. Call on application shutdown."""
        if self._http_client and not self._http_client.is_closed:
            await self._http_client.aclose()

    # -------------------------------------------------------------------
    # Core validation — the fail-closed gate
    # -------------------------------------------------------------------

    async def validate_response(
        self,
        tenant_id: str,
        conversation_id: str,
        response_text: str,
        customer_message: str,
        context: dict[str, Any] | None = None,
    ) -> CriticResult:
        """Validate an AI response through the Critic/Supervisor.

        THIS IS THE FAIL-CLOSED GATE. Every AI response must pass
        through this method before being delivered to the customer.

        If the Critic approves the response, it is safe to deliver.
        If the Critic rejects, times out, errors, or is unavailable,
        the response is BLOCKED.

        Args:
            tenant_id: Tenant partition key.
            conversation_id: Conversation this response belongs to.
            response_text: The AI-generated response text to validate.
            customer_message: The customer message that triggered this
                response (for context).
            context: Optional additional context for the Critic:
                - agents_invoked: list of agents used in the pipeline
                - model_used: which model generated the response
                - customer_id: tokenized customer identifier
                - tenant_tier: subscription tier

        Returns:
            CriticResult indicating whether the response is approved.

        Note:
            This method NEVER raises exceptions to the caller. All
            failure modes are captured in the CriticResult with
            approved=False. The caller must check result.approved.
        """
        request_id = f"critic-{conversation_id}-{int(time.time() * 1000)}"
        start_time = time.monotonic()

        # Check circuit breaker first
        if self._circuit_breaker.is_open:
            result = CriticResult(
                approved=False,
                verdict=None,
                block_reason=CriticBlockReason.CIRCUIT_OPEN,
                flags=["critic_circuit_open"],
                modified_response=None,
                latency_ms=0.0,
                critic_instance="none",
                request_id=request_id,
            )
            await self._on_block(
                tenant_id, conversation_id, result, response_text,
            )
            return result

        # Build the validation payload
        payload = {
            "conversation_id": conversation_id,
            "tenant_id": tenant_id,
            "response_text": response_text,
            "customer_message": customer_message,
            "request_id": request_id,
        }
        if context:
            payload["context"] = context

        # Try each Critic replica (failover on error/timeout)
        last_error: str | None = None
        for i, base_url in enumerate(self._critic_urls[:MAX_REPLICA_ATTEMPTS]):
            try:
                result = await self._call_critic(
                    base_url, payload, request_id, start_time,
                )

                # Critic responded — record success for circuit breaker
                self._circuit_breaker.record_success()

                # Update conversation record
                await self._update_conversation(
                    tenant_id, conversation_id, result,
                )

                # Log blocked responses as security events
                if not result.approved:
                    await self._on_block(
                        tenant_id, conversation_id, result, response_text,
                    )

                return result

            except (httpx.TimeoutException, httpx.ConnectError) as exc:
                elapsed = (time.monotonic() - start_time) * 1000
                last_error = f"{type(exc).__name__}: {exc}"
                logger.warning(
                    "Critic replica %d/%d failed: url=%s error=%s elapsed=%.0fms",
                    i + 1, len(self._critic_urls), base_url, last_error, elapsed,
                )
                self._circuit_breaker.record_failure()
                continue

            except Exception as exc:
                elapsed = (time.monotonic() - start_time) * 1000
                last_error = f"{type(exc).__name__}: {exc}"
                logger.exception(
                    "Unexpected error from Critic replica %d/%d: url=%s elapsed=%.0fms",
                    i + 1, len(self._critic_urls), base_url, elapsed,
                )
                self._circuit_breaker.record_failure()
                continue

        # All replicas failed — fail CLOSED
        elapsed = (time.monotonic() - start_time) * 1000
        logger.error(
            "ALL Critic replicas unavailable: tenant=%s conversation=%s "
            "attempts=%d last_error=%s elapsed=%.0fms — RESPONSE BLOCKED",
            tenant_id, conversation_id,
            min(len(self._critic_urls), MAX_REPLICA_ATTEMPTS),
            last_error, elapsed,
        )

        result = CriticResult(
            approved=False,
            verdict=None,
            block_reason=CriticBlockReason.UNAVAILABLE,
            flags=["all_critic_replicas_unavailable"],
            modified_response=None,
            latency_ms=elapsed,
            critic_instance="none",
            request_id=request_id,
        )

        await self._on_block(tenant_id, conversation_id, result, response_text)
        return result

    async def _call_critic(
        self,
        base_url: str,
        payload: dict[str, Any],
        request_id: str,
        start_time: float,
    ) -> CriticResult:
        """Make an HTTP call to a single Critic replica.

        Args:
            base_url: Critic replica base URL (e.g., "http://10.0.1.7:8080").
            payload: Validation request payload.
            request_id: Correlation ID.
            start_time: Monotonic timestamp when validation started.

        Returns:
            CriticResult from this replica.

        Raises:
            httpx.TimeoutException: If the call timed out.
            httpx.ConnectError: If the replica is unreachable.
        """
        client = await self._get_http_client()
        url = f"{base_url.rstrip('/')}{CRITIC_VALIDATE_PATH}"

        response = await client.post(url, json=payload)
        elapsed = (time.monotonic() - start_time) * 1000

        if response.status_code != 200:
            # Non-200 from Critic = treat as error → fail closed
            logger.warning(
                "Critic returned non-200: url=%s status=%d body=%s",
                url, response.status_code, response.text[:500],
            )
            return CriticResult(
                approved=False,
                verdict=None,
                block_reason=CriticBlockReason.ERROR,
                flags=[f"critic_http_{response.status_code}"],
                modified_response=None,
                latency_ms=elapsed,
                critic_instance=base_url,
                request_id=request_id,
            )

        # Parse Critic response
        body = response.json()

        verdict_str = body.get("verdict", "rejected")
        try:
            verdict = CriticVerdict(verdict_str)
        except ValueError:
            verdict = CriticVerdict.REJECTED

        approved = verdict in (CriticVerdict.APPROVED, CriticVerdict.MODIFIED)
        flags = body.get("flags", [])
        modified_response = body.get("modified_response")

        if verdict == CriticVerdict.MODIFIED and not modified_response:
            # Critic said "modified" but didn't provide the modified text.
            # Treat as rejection for safety.
            approved = False
            flags.append("modified_verdict_without_text")

        block_reason = None
        if not approved:
            block_reason = CriticBlockReason.REJECTED

        return CriticResult(
            approved=approved,
            verdict=verdict,
            block_reason=block_reason,
            flags=flags,
            modified_response=modified_response if approved else None,
            latency_ms=elapsed,
            critic_instance=base_url,
            request_id=request_id,
        )

    # -------------------------------------------------------------------
    # Response blocking handlers
    # -------------------------------------------------------------------

    async def _on_block(
        self,
        tenant_id: str,
        conversation_id: str,
        result: CriticResult,
        original_response: str,
    ) -> None:
        """Handle a blocked response.

        Logs a SECURITY_EVENT audit entry and triggers escalation
        if the Critic is entirely unavailable.
        """
        # Log audit event
        if self._audit:
            try:
                await self._audit.log_event(
                    event_type=AuditEventType.SECURITY_EVENT,
                    tenant_id=tenant_id,
                    actor="critic_policy",
                    actor_type="system",
                    payload={
                        "action": "response_blocked",
                        "block_reason": result.block_reason.value if result.block_reason else "unknown",
                        "flags": result.flags,
                        "critic_instance": result.critic_instance,
                        "latency_ms": result.latency_ms,
                        "request_id": result.request_id,
                        # Do NOT log the original response text — it failed
                        # safety validation and should not be persisted.
                        "response_length": len(original_response),
                    },
                    conversation_id=conversation_id,
                    request_id=result.request_id,
                )
            except Exception:
                logger.exception(
                    "Failed to log SECURITY_EVENT audit for blocked response: "
                    "tenant=%s conversation=%s",
                    tenant_id, conversation_id,
                )

        # Trigger escalation if Critic is completely unavailable
        if result.block_reason in (
            CriticBlockReason.UNAVAILABLE,
            CriticBlockReason.CIRCUIT_OPEN,
        ):
            await self._trigger_escalation(
                tenant_id, conversation_id, result,
            )

    async def _trigger_escalation(
        self,
        tenant_id: str,
        conversation_id: str,
        result: CriticResult,
    ) -> None:
        """Trigger escalation to human support when Critic is unavailable.

        When the safety validation system itself is down, conversations
        must be routed to human agents until the Critic recovers.
        """
        if self._audit:
            try:
                await self._audit.log_event(
                    event_type=AuditEventType.ESCALATION_TRIGGERED,
                    tenant_id=tenant_id,
                    actor="critic_policy",
                    actor_type="system",
                    payload={
                        "reason": "critic_unavailable",
                        "block_reason": result.block_reason.value if result.block_reason else "unknown",
                        "circuit_breaker_state": self._circuit_breaker.state.value,
                        "request_id": result.request_id,
                    },
                    conversation_id=conversation_id,
                    request_id=result.request_id,
                )
            except Exception:
                logger.exception(
                    "Failed to log ESCALATION_TRIGGERED audit: "
                    "tenant=%s conversation=%s",
                    tenant_id, conversation_id,
                )

        logger.error(
            "ESCALATION: Critic unavailable — routing conversation to human: "
            "tenant=%s conversation=%s reason=%s",
            tenant_id, conversation_id,
            result.block_reason.value if result.block_reason else "unknown",
        )

    # -------------------------------------------------------------------
    # Conversation record updates
    # -------------------------------------------------------------------

    async def _update_conversation(
        self,
        tenant_id: str,
        conversation_id: str,
        result: CriticResult,
    ) -> None:
        """Update the conversation's critic_passed field.

        Populates the ConversationDocument.critic_passed field that was
        defined in cosmos_schema.py for this purpose.
        """
        if self._conversations is None:
            return

        try:
            await self._conversations.patch(
                tenant_id=tenant_id,
                document_id=conversation_id,
                operations=[
                    {"op": "set", "path": "/critic_passed", "value": result.approved},
                ],
            )
        except Exception:
            # Non-fatal — don't block the pipeline for a metadata update
            logger.exception(
                "Failed to update critic_passed: tenant=%s conversation=%s",
                tenant_id, conversation_id,
            )

    # -------------------------------------------------------------------
    # Health monitoring
    # -------------------------------------------------------------------

    async def check_critic_health(self) -> CriticHealthStatus:
        """Check the health of all Critic/Supervisor replicas.

        Probes each replica's /health endpoint and returns aggregate
        status. Used by the /ready endpoint and monitoring systems.

        Returns:
            CriticHealthStatus with per-replica detail.
        """
        client = await self._get_http_client()
        details: dict[str, bool] = {}
        available = 0

        for base_url in self._critic_urls:
            url = f"{base_url.rstrip('/')}{CRITIC_HEALTH_PATH}"
            try:
                response = await client.get(url, timeout=2.0)
                is_healthy = response.status_code == 200
                details[base_url] = is_healthy
                if is_healthy:
                    available += 1
            except Exception:
                details[base_url] = False

        now = datetime.now(timezone.utc).isoformat()

        return CriticHealthStatus(
            healthy=available > 0,
            replicas_available=available,
            replicas_total=len(self._critic_urls),
            circuit_breaker_open=self._circuit_breaker.is_open,
            last_check_at=now,
            details=details,
        )

    # -------------------------------------------------------------------
    # Pipeline enforcement wrapper
    # -------------------------------------------------------------------

    async def require_critic_approval(
        self,
        tenant_id: str,
        conversation_id: str,
        response_text: str,
        customer_message: str,
        context: dict[str, Any] | None = None,
    ) -> tuple[bool, str, CriticResult]:
        """Pipeline-level enforcement: validate and return safe output.

        Convenience wrapper that calls validate_response() and returns
        either the approved response (possibly modified by Critic) or
        the safe fallback message.

        This is the recommended integration point for the response
        pipeline. It guarantees that the returned text is always safe
        to deliver to the customer.

        Args:
            tenant_id: Tenant partition key.
            conversation_id: Conversation identifier.
            response_text: Generated response to validate.
            customer_message: Customer's original message.
            context: Additional pipeline context.

        Returns:
            Tuple of (approved, safe_response_text, critic_result):
            - approved: True if Critic approved the response.
            - safe_response_text: The text to deliver to the customer.
              If approved, this is the original (or Critic-modified)
              response. If blocked, this is SAFE_FALLBACK_MESSAGE.
            - critic_result: Full CriticResult for logging/tracing.
        """
        result = await self.validate_response(
            tenant_id=tenant_id,
            conversation_id=conversation_id,
            response_text=response_text,
            customer_message=customer_message,
            context=context,
        )

        if result.approved:
            # Use modified response if Critic provided one
            safe_text = result.modified_response or response_text
            return True, safe_text, result

        # Blocked — return safe fallback
        return False, SAFE_FALLBACK_MESSAGE, result

    # -------------------------------------------------------------------
    # Circuit breaker management
    # -------------------------------------------------------------------

    def get_circuit_breaker_state(self) -> str:
        """Get the current circuit breaker state as a string."""
        return self._circuit_breaker.state.value

    def reset_circuit_breaker(self) -> None:
        """Force-reset the circuit breaker to CLOSED.

        Use this after manually verifying Critic recovery. Should only
        be called by admin operations, not by automated code.
        """
        self._circuit_breaker.reset()
        logger.info("Critic circuit breaker manually reset to CLOSED")
