"""Agent Red local environment source-of-truth helpers.

The CLI intentionally never renders dotenv values. Values are parsed only so
they can be preserved opaquely during a local migration.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypedDict

APP_ID = "agent-red"
APP_DISPLAY_NAME = "Agent Red"
GENERATED_MARKER = "# Generated by gt env migrate."
GENERATED_SOURCE = "# Source: applications/Agent_Red/.env.local"
GENERATED_EDIT_WARNING = "# Do not edit this file as an independent source of truth."

_DOTENV_ASSIGNMENT = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")

_APP_KEY_PREFIXES = (
    "AGENT_RED_",
    "SHOPIFY_",
    "NEXT_PUBLIC_",
    "VITE_",
    "ADMIN_",
    "STANDALONE_",
    "PROVIDER_",
)

_PLATFORM_KEY_PREFIXES = (
    "GTKB_",
    "GROUNDTRUTH_",
    "CLAUDE_",
    "CODEX_",
    "CURSOR_",
    "ANTIGRAVITY_",
    "TAFE_",
    "MEMBASE_",
    "BRIDGE_",
    "GITHUB_",
    "GIT_",
)

_PLATFORM_KEY_EXACT = {
    "HOME",
    "PATH",
    "PYTHONHOME",
    "PYTHONPATH",
    "USERPROFILE",
    "VIRTUAL_ENV",
}


class EnvSotError(Exception):
    """Raised when env SoT planning or migration cannot proceed safely."""


KeyClass = Literal["platform", "app", "ambiguous"]
EnvAction = TypedDict(
    "EnvAction",
    {"action": str, "from": str, "to": str | list[str], "key_count": int, "view_count": int},
    total=False,
)


@dataclass(frozen=True)
class EnvLine:
    """One parsed dotenv line."""

    raw: str
    line_no: int
    key: str | None = None
    value: str | None = None


@dataclass(frozen=True)
class EnvFileSummary:
    """Value-free summary of one dotenv file."""

    path: str
    exists: bool
    key_count: int
    generated_from_app_sot: bool
    independent_sot: bool
    duplicate_keys: tuple[str, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "path": self.path,
            "exists": self.exists,
            "key_count": self.key_count,
            "generated_from_app_sot": self.generated_from_app_sot,
            "independent_sot": self.independent_sot,
            "duplicate_keys": list(self.duplicate_keys),
        }


@dataclass(frozen=True)
class EnvPlan:
    """Value-free migration plan."""

    app: str
    root_env: EnvFileSummary
    app_env: EnvFileSummary
    admin_views: tuple[EnvFileSummary, ...]
    platform_key_count: int
    root_app_key_count: int
    ambiguous_root_keys: tuple[str, ...]
    actions: tuple[EnvAction, ...]
    diagnostics: tuple[str, ...]

    @property
    def independent_admin_sot_count(self) -> int:
        return sum(1 for view in self.admin_views if view.independent_sot)

    @property
    def duplicate_key_count(self) -> int:
        summaries = (self.root_env, self.app_env, *self.admin_views)
        return sum(len(summary.duplicate_keys) for summary in summaries)

    @property
    def ok_for_apply(self) -> bool:
        return not self.ambiguous_root_keys and self.independent_admin_sot_count == 0 and self.duplicate_key_count == 0

    def to_dict(self) -> dict[str, object]:
        return {
            "app": self.app,
            "ok_for_apply": self.ok_for_apply,
            "root": {
                **self.root_env.to_dict(),
                "platform_key_count": self.platform_key_count,
                "app_key_count": self.root_app_key_count,
                "ambiguous_key_count": len(self.ambiguous_root_keys),
                "ambiguous_keys": list(self.ambiguous_root_keys),
            },
            "app_sot": self.app_env.to_dict(),
            "admin_views": [view.to_dict() for view in self.admin_views],
            "summary": {
                "independent_admin_sot_count": self.independent_admin_sot_count,
                "duplicate_key_count": self.duplicate_key_count,
                "planned_action_count": len(self.actions),
            },
            "actions": list(self.actions),
            "diagnostics": list(self.diagnostics),
        }


@dataclass(frozen=True)
class EnvMigrationResult:
    """Value-free result of an env migration."""

    app: str
    applied: bool
    moved_key_count: int
    generated_view_count: int
    touched_paths: tuple[str, ...]
    plan: EnvPlan

    def to_dict(self) -> dict[str, object]:
        return {
            "app": self.app,
            "applied": self.applied,
            "moved_key_count": self.moved_key_count,
            "generated_view_count": self.generated_view_count,
            "touched_paths": list(self.touched_paths),
            "plan": self.plan.to_dict(),
        }


def build_plan(project_root: Path, *, app: str = APP_ID) -> EnvPlan:
    """Build a value-free migration plan for Agent Red local env files."""

    _require_supported_app(app)
    root = project_root.resolve()
    root_env_path = root / ".env.local"
    app_env_path = _app_env_path(root)
    admin_paths = _admin_env_paths(root)

    root_lines = _parse_dotenv(root_env_path)
    app_lines = _parse_dotenv(app_env_path)
    admin_lines = {path: _parse_dotenv(path) for path in admin_paths}

    classifications = [_classify_root_key(line.key) for line in root_lines if line.key]
    platform_key_count = classifications.count("platform")
    root_app_key_count = classifications.count("app")
    ambiguous_root_keys = tuple(
        sorted({line.key for line in root_lines if line.key and _classify_root_key(line.key) == "ambiguous"})
    )

    root_summary = _summarize_file(root, root_env_path, root_lines, independent_sot=False)
    app_summary = _summarize_file(root, app_env_path, app_lines, independent_sot=bool(_entries(app_lines)))
    admin_summaries = tuple(
        _summarize_file(
            root,
            path,
            lines,
            independent_sot=bool(_entries(lines)) and not _is_generated_view(lines),
        )
        for path, lines in admin_lines.items()
    )

    actions: list[EnvAction] = []
    if root_app_key_count:
        actions.append(
            {
                "action": "move-root-app-keys",
                "from": _rel(root, root_env_path),
                "to": _rel(root, app_env_path),
                "key_count": root_app_key_count,
            }
        )

    app_source_key_count = len(_entries(app_lines)) + root_app_key_count
    if app_source_key_count:
        actions.append(
            {
                "action": "generate-admin-env-views",
                "from": _rel(root, app_env_path),
                "to": [_rel(root, path) for path in admin_paths],
                "view_count": len(admin_paths),
            }
        )

    diagnostics = _diagnostics(
        ambiguous_root_keys=ambiguous_root_keys,
        independent_admin_summaries=admin_summaries,
        summaries=(root_summary, app_summary, *admin_summaries),
    )

    return EnvPlan(
        app=app,
        root_env=root_summary,
        app_env=app_summary,
        admin_views=admin_summaries,
        platform_key_count=platform_key_count,
        root_app_key_count=root_app_key_count,
        ambiguous_root_keys=ambiguous_root_keys,
        actions=tuple(actions),
        diagnostics=tuple(diagnostics),
    )


def check_plan(project_root: Path, *, app: str = APP_ID) -> EnvPlan:
    """Return the current plan; callers can inspect ``ok_for_apply``."""

    return build_plan(project_root, app=app)


def migrate(project_root: Path, *, app: str = APP_ID, apply: bool = False) -> EnvMigrationResult:
    """Dry-run or apply the local env SoT migration."""

    plan = build_plan(project_root, app=app)
    if not apply:
        return EnvMigrationResult(
            app=app,
            applied=False,
            moved_key_count=plan.root_app_key_count,
            generated_view_count=_planned_generated_view_count(plan),
            touched_paths=(),
            plan=plan,
        )

    if not plan.ok_for_apply:
        raise EnvSotError("Env migration is not safe to apply; run `gt env check --app agent-red` for diagnostics.")

    root = project_root.resolve()
    root_env_path = root / ".env.local"
    app_env_path = _app_env_path(root)
    admin_paths = _admin_env_paths(root)

    root_lines = _parse_dotenv(root_env_path)
    app_lines = _parse_dotenv(app_env_path)
    moved_entries = tuple(line for line in _entries(root_lines) if _classify_root_key(line.key or "") == "app")
    app_keys = {line.key for line in _entries(app_lines)}
    duplicate_across_sources = sorted(
        {line.key for line in moved_entries if line.key is not None and line.key in app_keys}
    )
    if duplicate_across_sources:
        keys = ", ".join(duplicate_across_sources)
        raise EnvSotError(f"Env migration is not safe to apply; duplicate app keys already exist in app SoT: {keys}")

    touched_paths: list[Path] = []
    if moved_entries:
        _write_root_without_moved_app_keys(root_env_path, root_lines, moved_entries)
        touched_paths.append(root_env_path)
        _append_moved_entries(app_env_path, moved_entries)
        touched_paths.append(app_env_path)

    final_app_lines = _parse_dotenv(app_env_path)
    final_app_entries = tuple(_entries(final_app_lines))
    if final_app_entries:
        for admin_path in admin_paths:
            _write_generated_view(admin_path, final_app_entries)
            touched_paths.append(admin_path)

    return EnvMigrationResult(
        app=app,
        applied=True,
        moved_key_count=len(moved_entries),
        generated_view_count=len(admin_paths) if final_app_entries else 0,
        touched_paths=tuple(_rel(root, path) for path in touched_paths),
        plan=build_plan(root, app=app),
    )


def render_plan(plan: EnvPlan) -> str:
    """Render a human-readable plan without dotenv values."""

    lines = [
        f"{APP_DISPLAY_NAME} env SoT plan",
        f"root {plan.root_env.path}: keys={plan.root_env.key_count}, platform={plan.platform_key_count}, "
        f"app={plan.root_app_key_count}, ambiguous={len(plan.ambiguous_root_keys)}",
        f"app SoT {plan.app_env.path}: keys={plan.app_env.key_count}, exists={_yes_no(plan.app_env.exists)}",
        f"admin views: independent={plan.independent_admin_sot_count}, total={len(plan.admin_views)}",
    ]
    if plan.actions:
        lines.append("actions:")
        for action in plan.actions:
            lines.append(f"- {_render_action(action)}")
    else:
        lines.append("actions: none")

    if plan.diagnostics:
        lines.append("diagnostics:")
        for diagnostic in plan.diagnostics:
            lines.append(f"- {diagnostic}")
    lines.append(f"safe to apply: {_yes_no(plan.ok_for_apply)}")
    return "\n".join(lines)


def render_migration_result(result: EnvMigrationResult) -> str:
    """Render a human-readable migration result without dotenv values."""

    mode = "applied" if result.applied else "dry-run"
    lines = [
        f"{APP_DISPLAY_NAME} env SoT migration ({mode})",
        f"moved app keys: {result.moved_key_count}",
        f"generated admin views: {result.generated_view_count}",
    ]
    if result.touched_paths:
        lines.append("touched paths:")
        lines.extend(f"- {path}" for path in result.touched_paths)
    else:
        lines.append("touched paths: none")
    return "\n".join(lines)


def _require_supported_app(app: str) -> None:
    if app != APP_ID:
        raise EnvSotError(f"Unsupported env app '{app}'. Supported app: {APP_ID}.")


def _app_env_path(root: Path) -> Path:
    return root / "applications" / "Agent_Red" / ".env.local"


def _admin_env_paths(root: Path) -> tuple[Path, Path, Path]:
    base = root / "applications" / "Agent_Red" / "admin"
    return (
        base / "shopify" / ".env.local",
        base / "standalone" / ".env.local",
        base / "provider" / ".env.local",
    )


def _parse_dotenv(path: Path) -> tuple[EnvLine, ...]:
    if not path.exists():
        return ()
    text = path.read_text(encoding="utf-8")
    lines = []
    for index, raw in enumerate(text.splitlines(keepends=True), start=1):
        match = _DOTENV_ASSIGNMENT.match(raw.rstrip("\r\n"))
        if match:
            lines.append(EnvLine(raw=raw, line_no=index, key=match.group(1), value=match.group(2)))
        else:
            lines.append(EnvLine(raw=raw, line_no=index))
    return tuple(lines)


def _entries(lines: tuple[EnvLine, ...]) -> tuple[EnvLine, ...]:
    return tuple(line for line in lines if line.key is not None)


def _classify_root_key(key: str) -> KeyClass:
    normalized = key.strip().upper()
    if normalized in _PLATFORM_KEY_EXACT or normalized.startswith(_PLATFORM_KEY_PREFIXES):
        return "platform"
    if normalized.startswith(_APP_KEY_PREFIXES):
        return "app"
    return "ambiguous"


def _summarize_file(root: Path, path: Path, lines: tuple[EnvLine, ...], *, independent_sot: bool) -> EnvFileSummary:
    entries = _entries(lines)
    return EnvFileSummary(
        path=_rel(root, path),
        exists=path.exists(),
        key_count=len(entries),
        generated_from_app_sot=_is_generated_view(lines),
        independent_sot=independent_sot,
        duplicate_keys=tuple(_duplicate_keys(entries)),
    )


def _is_generated_view(lines: tuple[EnvLine, ...]) -> bool:
    return any(line.raw.rstrip("\r\n") == GENERATED_MARKER for line in lines)


def _duplicate_keys(entries: tuple[EnvLine, ...]) -> list[str]:
    seen: set[str] = set()
    duplicates: set[str] = set()
    for entry in entries:
        if entry.key in seen:
            duplicates.add(entry.key or "")
        seen.add(entry.key or "")
    return sorted(duplicates)


def _diagnostics(
    *,
    ambiguous_root_keys: tuple[str, ...],
    independent_admin_summaries: tuple[EnvFileSummary, ...],
    summaries: tuple[EnvFileSummary, ...],
) -> list[str]:
    diagnostics: list[str] = []
    if ambiguous_root_keys:
        diagnostics.append("ambiguous root keys block apply: " + ", ".join(ambiguous_root_keys))
    independent_paths = [summary.path for summary in independent_admin_summaries if summary.independent_sot]
    if independent_paths:
        diagnostics.append("independent admin env files block apply: " + ", ".join(independent_paths))
    duplicate_parts = [
        f"{summary.path}: {', '.join(summary.duplicate_keys)}" for summary in summaries if summary.duplicate_keys
    ]
    if duplicate_parts:
        diagnostics.append("duplicate keys block apply: " + "; ".join(duplicate_parts))
    return diagnostics


def _planned_generated_view_count(plan: EnvPlan) -> int:
    for action in plan.actions:
        if action.get("action") == "generate-admin-env-views":
            return int(action.get("view_count", 0))
    return 0


def _write_root_without_moved_app_keys(
    root_env_path: Path,
    root_lines: tuple[EnvLine, ...],
    moved_entries: tuple[EnvLine, ...],
) -> None:
    moved_line_numbers = {line.line_no for line in moved_entries}
    remaining = "".join(line.raw for line in root_lines if line.line_no not in moved_line_numbers)
    root_env_path.write_text(remaining, encoding="utf-8")


def _append_moved_entries(app_env_path: Path, moved_entries: tuple[EnvLine, ...]) -> None:
    app_env_path.parent.mkdir(parents=True, exist_ok=True)
    existing = app_env_path.read_text(encoding="utf-8") if app_env_path.exists() else ""
    if existing and not existing.endswith("\n"):
        existing += "\n"
    migrated = ["# Migrated from root .env.local by gt env migrate.\n"]
    migrated.extend(f"{entry.key}={entry.value}\n" for entry in moved_entries)
    app_env_path.write_text(existing + "".join(migrated), encoding="utf-8")


def _write_generated_view(admin_path: Path, app_entries: tuple[EnvLine, ...]) -> None:
    admin_path.parent.mkdir(parents=True, exist_ok=True)
    content = [
        f"{GENERATED_MARKER}\n",
        f"{GENERATED_SOURCE}\n",
        f"{GENERATED_EDIT_WARNING}\n",
    ]
    content.extend(f"{entry.key}={entry.value}\n" for entry in app_entries)
    admin_path.write_text("".join(content), encoding="utf-8")


def _render_action(action: EnvAction) -> str:
    kind = action.get("action")
    if kind == "move-root-app-keys":
        return f"move {action.get('key_count', 0)} app key(s) from {action.get('from')} to {action.get('to')}"
    if kind == "generate-admin-env-views":
        targets = action.get("to", [])
        target_text = ", ".join(str(target) for target in targets) if isinstance(targets, list) else str(targets)
        return f"generate {action.get('view_count', 0)} admin env view(s): {target_text}"
    return str(kind)


def _rel(root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path)


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"
