param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Codex", "Claude")]
    [string]$Scanner,

    [switch]$NoExec,

    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ForwardArgs = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptName = if ($Scanner -eq "Codex") {
    "codex-file-bridge-scan.ps1"
} else {
    "claude-file-bridge-scan.ps1"
}

$sourcePath = Join-Path $PSScriptRoot $scriptName
$generatedPath = Join-Path $PSScriptRoot ($scriptName -replace "\.ps1$", "-noconsole.generated.ps1")
$workspace = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path

if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Scanner script not found: $sourcePath"
}

$source = Get-Content -LiteralPath $sourcePath -Raw
$needle = '$psi.UseShellExecute = $false'
$replacement = @'
$psi.UseShellExecute = $false
    $psi.CreateNoWindow = $true
    $psi.WindowStyle = [System.Diagnostics.ProcessWindowStyle]::Hidden
'@

if ($source -notlike "*$needle*") {
    throw "No ProcessStartInfo UseShellExecute marker found in $sourcePath"
}

$patched = $source.Replace($needle, $replacement)

$logWriteHelper = @'
function Add-LogLine {
    param(
        [string]$Path,
        [string]$Value
    )

    for ($attempt = 1; $attempt -le 5; $attempt++) {
        try {
            [System.IO.File]::AppendAllText($Path, $Value + [Environment]::NewLine, [System.Text.Encoding]::UTF8)
            return
        } catch {
            if ($attempt -eq 5) {
                throw
            }
            Start-Sleep -Milliseconds (100 * $attempt)
        }
    }
}

'@
if ($patched -notlike "*function Add-LogLine*") {
    $patched = $patched.Replace("function Write-ScanLog {", "$logWriteHelper`r`nfunction Write-ScanLog {")
}
$patched = $patched.Replace(
    'Add-Content -LiteralPath (Join-Path $LogDir "scan.log") -Value "$stamp $Message"',
    'Add-LogLine -Path (Join-Path $LogDir "scan.log") -Value "$stamp $Message"')
$patched = $patched.Replace(
    'Add-Content -LiteralPath (Join-Path $LogDir "claude-scan.log") -Value "$stamp $Message"',
    'Add-LogLine -Path (Join-Path $LogDir "claude-scan.log") -Value "$stamp $Message"')

# The source scanners were written for an interactive PowerShell runtime and use
# $proc.Kill($true) on timeout. Under Windows PowerShell/.NET Framework that
# overload is not consistently available, and the scanner swallows the failure,
# leaving orphaned claude/codex child processes alive after a timeout. The
# generated no-console copy owns the unattended runtime contract, so harden it
# here without editing the source scanner files.
$processTreeKill = @'
try {
            if ($env:OS -eq "Windows_NT") {
                & taskkill.exe /PID $proc.Id /T /F | Out-Null
            } else {
                $proc.Kill()
            }
        } catch {
            try { $proc.Kill() } catch { }
        }
'@
$patched = $patched.Replace('try { $proc.Kill($true) } catch { }', $processTreeKill)

if ($Scanner -eq "Claude") {
    $patched = $patched.Replace(
        '$claudeTimeoutMs = 900000  # 15 minutes',
        @'
$timeoutMinutesRaw = if ($env:AGENT_RED_BRIDGE_EXEC_TIMEOUT_MINUTES) { $env:AGENT_RED_BRIDGE_EXEC_TIMEOUT_MINUTES } else { "60" }
    $timeoutMinutes = 60
    if (-not [int]::TryParse($timeoutMinutesRaw, [ref]$timeoutMinutes)) {
        $timeoutMinutes = 60
    }
    if ($timeoutMinutes -lt 5) { $timeoutMinutes = 5 }
    $claudeTimeoutMs = $timeoutMinutes * 60000
'@)
    $patched = $patched.Replace(
        'claude exec timed out after 15 minutes for $($selected.Count) selected item(s) ',
        'claude exec timed out after $timeoutMinutes minutes for $($selected.Count) selected item(s) ')
} else {
    $patched = $patched.Replace(
        '$codexTimeoutMs = 900000  # 15 minutes; long enough for normal reviews, short enough to avoid silent pileups.',
        @'
$timeoutMinutesRaw = if ($env:AGENT_RED_BRIDGE_EXEC_TIMEOUT_MINUTES) { $env:AGENT_RED_BRIDGE_EXEC_TIMEOUT_MINUTES } else { "60" }
    $timeoutMinutes = 60
    if (-not [int]::TryParse($timeoutMinutesRaw, [ref]$timeoutMinutes)) {
        $timeoutMinutes = 60
    }
    if ($timeoutMinutes -lt 5) { $timeoutMinutes = 5 }
    $codexTimeoutMs = $timeoutMinutes * 60000
'@)
    $patched = $patched.Replace(
        'codex exec timed out after 15 minutes for $($SelectedEntries.Count) selected item(s) (full queue: $AttentionCount)',
        'codex exec timed out after $timeoutMinutes minutes for $($SelectedEntries.Count) selected item(s) (full queue: $AttentionCount)')
}
# Per S307 hardcoded-path directive: the generator embeds a repo-relative
# source reference into the generated wrapper, not the absolute $sourcePath.
# An absolute path here would re-introduce a workstation-coupled literal in
# every regenerated wrapper.
$relativeSource = "independent-progress-assessments/bridge-automation/$scriptName"
$patched = @"
# Generated by run-bridge-scan-noconsole.ps1.
# Source: $relativeSource (resolved at runtime via `$PSScriptRoot)
# Purpose: keep scheduled bridge scanner child CLIs from creating foreground console windows.

$patched
"@

$writeGenerated = $true
if (Test-Path -LiteralPath $generatedPath) {
    $existing = Get-Content -LiteralPath $generatedPath -Raw
    $writeGenerated = ($existing -ne $patched)
}

if ($writeGenerated) {
    Set-Content -LiteralPath $generatedPath -Value $patched -Encoding UTF8
}

$forwardNoExec = $NoExec -or (@($ForwardArgs) -contains "-NoExec")
$ForwardArgs = @($ForwardArgs | Where-Object { $_ -ne "-NoExec" })

$global:LASTEXITCODE = $null
if ($forwardNoExec) {
    & $generatedPath -NoExec @ForwardArgs
} else {
    & $generatedPath @ForwardArgs
}
$scriptOk = $?
if ($null -ne $global:LASTEXITCODE) {
    exit $global:LASTEXITCODE
}

if ($scriptOk) {
    exit 0
}

exit 1
