"""
Stripe product catalog loader.

Reads config/stripe_product_ids.json (generated by
scripts/stripe/create_product_catalog.py) and provides typed access to
Stripe product IDs, price IDs, and meter IDs used by checkout, webhook,
and usage-reporting modules.

© 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, ClassVar

from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_DEFAULT_CATALOG_PATH = _PROJECT_ROOT / "config" / "stripe_product_ids.json"

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class TierCatalog(BaseModel):
    """A subscription tier's Stripe IDs."""

    product_id: str
    monthly_price_id: str
    annual_price_id: str
    overage_price_id: str
    included_conversations: int

    def price_id_for_interval(self, interval: str) -> str:
        """Return the price ID for 'month' or 'year'."""
        if interval == "year":
            return self.annual_price_id
        return self.monthly_price_id


class PackCatalog(BaseModel):
    """A conversation pack's Stripe IDs."""

    product_id: str
    price_id: str
    conversations: int


class AddonCatalog(BaseModel):
    """An add-on module's Stripe IDs."""

    product_id: str
    price_id: str
    available_on: list[str]


class StripeCatalog(BaseModel):
    """Full Agent Red Stripe product catalog."""

    mode: str  # "test" or "live"
    meter_id: str
    tiers: dict[str, TierCatalog]
    packs: dict[str, PackCatalog]
    addons: dict[str, AddonCatalog]
    coupon_id: str

    # -- Convenience lookups --------------------------------------------------

    VALID_TIERS: ClassVar[frozenset[str]] = frozenset({"starter", "professional", "enterprise"})
    VALID_INTERVALS: ClassVar[frozenset[str]] = frozenset({"month", "year"})

    def get_tier(self, tier_name: str) -> TierCatalog:
        """Get a tier by name, raising ValueError if not found."""
        if tier_name not in self.tiers:
            raise ValueError(
                f"Unknown tier '{tier_name}'. Valid: {sorted(self.VALID_TIERS)}"
            )
        return self.tiers[tier_name]

    def get_pack(self, pack_id: str) -> PackCatalog:
        """Get a conversation pack by ID, raising ValueError if not found."""
        if pack_id not in self.packs:
            raise ValueError(
                f"Unknown pack '{pack_id}'. Valid: {sorted(self.packs.keys())}"
            )
        return self.packs[pack_id]

    def get_addon(self, addon_id: str) -> AddonCatalog:
        """Get an add-on by ID, raising ValueError if not found."""
        if addon_id not in self.addons:
            raise ValueError(
                f"Unknown add-on '{addon_id}'. Valid: {sorted(self.addons.keys())}"
            )
        return self.addons[addon_id]

    def validate_addon_for_tier(self, addon_id: str, tier_name: str) -> None:
        """Raise ValueError if the add-on is not available on the given tier."""
        addon = self.get_addon(addon_id)
        if tier_name not in addon.available_on:
            raise ValueError(
                f"Add-on '{addon_id}' is not available on tier '{tier_name}'. "
                f"Available on: {addon.available_on}"
            )


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def load_catalog(path: str | None = None) -> StripeCatalog:
    """Load and parse the Stripe product catalog from JSON.

    Cached after first call. Pass an explicit path for testing.
    """
    catalog_path = Path(path) if path else _DEFAULT_CATALOG_PATH

    if not catalog_path.exists():
        raise FileNotFoundError(
            f"Stripe catalog not found at {catalog_path}. "
            "Run: python scripts/stripe/create_product_catalog.py"
        )

    raw: dict[str, Any] = json.loads(catalog_path.read_text(encoding="utf-8"))

    return StripeCatalog(
        mode=raw["mode"],
        meter_id=raw["meter"]["conversation_overage"]["meter_id"],
        tiers={k: TierCatalog(**v) for k, v in raw["tiers"].items()},
        packs={k: PackCatalog(**v) for k, v in raw["packs"].items()},
        addons={k: AddonCatalog(**v) for k, v in raw["addons"].items()},
        coupon_id=raw["coupons"]["annual_17pct_off"]["coupon_id"],
    )
