"""Parse mypy --strict output into a categorized summary (Phase 4A).

Reads raw mypy output from `docs/reports/v0.4-baseline/types.raw.txt`
(generated via `python -m mypy --strict src/groundtruth_kb/`) and produces
a categorized Markdown report at `docs/reports/v0.4-baseline/types.md`.

Categorization groups errors by:
  - Error code (e.g. no-untyped-def, no-untyped-call, assignment, ...)
  - File (per-module error count)

Run: python scripts/audit_types.py <raw> <out.md>

Verified against:
  - mypy 1.20.1
  - groundtruth-kb 0.4.0 (993f31b8d42ac272b9716c191527b599d08ba632)

© 2026 Remaker Digital. Licensed under AGPL-3.0-or-later.
"""

from __future__ import annotations

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ERROR_LINE = re.compile(
    r"^(?P<file>[^:]+):(?P<line>\d+):(?:\d+:)?\s*"
    r"(?P<severity>error|note|warning):\s+"
    r"(?P<message>.+?)"
    r"(?:\s+\[(?P<code>[a-z0-9-]+)\])?$"
)


def parse_raw(raw_text: str) -> tuple[list[dict], dict]:
    """Parse raw mypy output.

    Returns (errors, meta) where errors is a list of dicts and meta has
    totals + the mypy version line if present.
    """
    errors: list[dict] = []
    meta: dict = {"mypy_exit": None, "summary": None}

    for line in raw_text.splitlines():
        m = ERROR_LINE.match(line)
        if m and m.group("severity") == "error":
            errors.append(
                {
                    "file": m.group("file").replace("\\", "/"),
                    "line": int(m.group("line")),
                    "message": m.group("message").strip(),
                    "code": m.group("code") or "no-code",
                }
            )
            continue
        if line.startswith("Found ") and "error" in line:
            meta["summary"] = line.strip()
            continue
        if line.startswith("mypy exit code:"):
            meta["mypy_exit"] = line.split(":")[-1].strip()
            continue

    return errors, meta


def group_by_code(errors: list[dict]) -> list[tuple[str, int]]:
    """Group errors by mypy error code, sorted by frequency descending."""
    c = Counter(e["code"] for e in errors)
    return c.most_common()


def group_by_file(errors: list[dict]) -> list[tuple[str, int]]:
    """Group errors by file, sorted by count descending."""
    c = Counter(e["file"].split("src/groundtruth_kb/")[-1] for e in errors)
    return c.most_common()


def format_report(errors: list[dict], meta: dict) -> str:
    """Format the parsed output as a Markdown report."""
    lines: list[str] = []
    lines.append("# Type Annotation Baseline (Phase 4A)")
    lines.append("")
    lines.append("Generated by `scripts/audit_types.py` parsing the raw `mypy --strict` output.")
    lines.append("")
    lines.append("## Baseline")
    lines.append("")
    lines.append("- **mypy version:** 1.20.1 (pinned for audit reproducibility)")
    lines.append("- **Invocation:** `python -m mypy --strict src/groundtruth_kb/`")
    lines.append(f"- **Total errors:** {len(errors)}")
    if meta.get("summary"):
        lines.append(f"- **Raw summary:** `{meta['summary']}`")
    if meta.get("mypy_exit") is not None:
        lines.append(f"- **mypy exit code:** {meta['mypy_exit']}")
    lines.append("")
    lines.append(
        "Non-zero exit is expected and is captured as measurement data, "
        "not audit failure. Phase 4A is measurement-only; Phase 4B will triage "
        "and decide which errors are worth fixing."
    )
    lines.append("")

    lines.append("## Errors by category (mypy error code)")
    lines.append("")
    lines.append("| Error code | Count | Share |")
    lines.append("|---|---:|---:|")
    total = len(errors) or 1
    for code, count in group_by_code(errors):
        share = count / total * 100
        lines.append(f"| `{code}` | {count} | {share:.1f}% |")
    lines.append("")

    lines.append("## Errors by file")
    lines.append("")
    lines.append("| File | Error count |")
    lines.append("|---|---:|")
    for fname, count in group_by_file(errors):
        lines.append(f"| `{fname}` | {count} |")
    lines.append("")

    # Show the first few errors per category to make the report actionable
    lines.append("## Sample errors (first 3 per category)")
    lines.append("")
    by_code: dict[str, list[dict]] = defaultdict(list)
    for e in errors:
        by_code[e["code"]].append(e)
    for code, _ in group_by_code(errors):
        lines.append(f"### `{code}` ({len(by_code[code])} occurrences)")
        lines.append("")
        for e in by_code[code][:3]:
            short_file = e["file"].split("src/groundtruth_kb/")[-1]
            lines.append(f"- `{short_file}:{e['line']}` — {e['message'][:120]}")
        if len(by_code[code]) > 3:
            lines.append(f"- … {len(by_code[code]) - 3} more")
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- This is a **baseline snapshot**, not an enforcement target. Phase 4A does not enable mypy in CI.")
    lines.append(
        "- The raw mypy output is also committed at `docs/reports/v0.4-baseline/types.raw.txt` for direct reference."
    )
    lines.append(
        "- Phase 4B will decide which error codes to fix (likely `no-untyped-def` "
        "and `assignment` on public API functions first) and which to suppress or "
        "defer (likely the large legacy-module surface areas)."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by `scripts/audit_types.py`. Part of the Phase 4A measurement-only audit baseline.*")
    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: python audit_types.py <raw-input> <markdown-output>", file=sys.stderr)
        sys.exit(2)

    raw_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    raw_text = raw_path.read_text(encoding="utf-8", errors="replace")
    errors, meta = parse_raw(raw_text)
    report = format_report(errors, meta)
    out_path.write_text(report, encoding="utf-8")
    print(f"wrote {out_path} ({len(errors)} errors categorized)")


if __name__ == "__main__":
    main()
