#!/usr/bin/env python3
"""Keep ephemeral, derived and runtime material out of the actual Git index.

This check creates no review or permission evidence. Native project finalization
checks the complete reviewed product; this hook also applies to direct owner
commits. A deletion removes obsolete tracked material without publishing it again.

The harness projection roots (.agent, .claude, .codex, .cursor, .goose and
.api-harness) are gitignored at the repository top level and refused here as
postimages, so the ignore rule and this refusal state one policy (owner ruling
D14, 2026-09-17): rendered output is regenerated by ``gt harness project`` and
never committed. Deletions of their historical tracked copies pass.
The root AGENTS.md and the declared root pointer files (profiles.toml
``[root_pointers]``) are tracked authored sources outside the projector's
output; their bytes are pinned by the acceptance checker
(``declared_pointer_drift``), not by this refusal (owner ruling R1 option B,
D34, 2026-09-19).
``config/governance/`` carries only hand-authored control catalogs; derived
inventories such as the timer inventory live under ``.groundtruth/derived/``,
a non-product prefix refused here as well.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import unicodedata
from pathlib import Path, PurePosixPath

RUNTIME_COMPONENTS = frozenset(
    {
        ".git",
        ".gtkb-state",
        "harness-state",
        "scratchpad",
        ".worktrees",
        ".agent",
        ".antigravity",
        ".api-harness",
        ".claude",
        ".codex",
        ".cursor",
        ".goose",
        ".ollama",
    }
)
GENERATED_ROOT_FILES = frozenset({"gemini.md", ".cursorrules"})
NONPRODUCT_PREFIXES = (
    "bridge",
    ".groundtruth/derived",
    ".groundtruth/runtime",
    ".groundtruth/formal-artifact-approvals",
    ".groundtruth/inventory",
    "config/agent-control",
)


class IndexCheckError(RuntimeError):
    pass


def inspect_staged(root: Path) -> dict:
    try:
        result = subprocess.run(
            [
                "git",
                "--no-optional-locks",
                "--no-replace-objects",
                "--literal-pathspecs",
                "-C",
                str(root),
                "diff",
                "--cached",
                "--raw",
                "--no-abbrev",
                "--no-renames",
                "-z",
            ],
            capture_output=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise IndexCheckError("staged_index_unavailable: Git could not read the staged changes") from error
    if result.returncode:
        raise IndexCheckError("staged_index_unavailable: Git refused the staged-index read")
    tokens = result.stdout.split(b"\0")
    if tokens.pop() != b"" or len(tokens) % 2:
        raise IndexCheckError("staged_index_invalid: Malformed Git raw output")
    refused, removals, product = [], [], []
    identities = set()
    for offset in range(0, len(tokens), 2):
        try:
            metadata = tokens[offset].decode("ascii").split()
            path = tokens[offset + 1].decode("utf-8")
        except UnicodeError as error:
            raise IndexCheckError("staged_index_invalid: Index identities must be representable exactly") from error
        if len(metadata) != 5 or not metadata[0].startswith(":"):
            raise IndexCheckError("staged_index_invalid: Malformed Git entry")
        old_mode, mode, _old_oid, _oid, status = metadata
        if status not in {"A", "M", "D", "T"}:
            raise IndexCheckError("staged_index_invalid: Resolve unsupported or unmerged changes")
        parts = PurePosixPath(path)
        if (
            not path
            or parts.is_absolute()
            or path != parts.as_posix()
            or ".." in parts.parts
            or "\\" in path
            or ":" in path
        ):
            raise IndexCheckError("staged_index_invalid: A staged path is not a canonical relative identity")
        identity = unicodedata.normalize("NFC", path).casefold()
        if status == "D":
            if mode != "000000":
                raise IndexCheckError("staged_index_invalid: A deletion still has a postimage")
            removals.append(path)
            continue
        if identity in identities:
            raise IndexCheckError("staged_index_invalid: Staged paths have colliding identities")
        identities.add(identity)
        if any(
            part.endswith((" ", "."))
            or re.match(r"^(?:con|prn|aux|nul|com[1-9¹²³]|lpt[1-9¹²³])(?:\.|$)", part, re.IGNORECASE)
            or any(ord(char) < 32 or char in '<>"|?*' for char in part)
            for part in parts.parts
        ):
            raise IndexCheckError("staged_index_invalid: A staged path is not a portable file identity")
        if mode not in {"100644", "100755"}:
            refused.append({"path": path, "reason": "unsupported_file_mode"})
            continue
        if (
            identity in GENERATED_ROOT_FILES
            or any(part.casefold() in RUNTIME_COMPONENTS for part in parts.parts)
            or any(part.casefold().startswith(".gtkb-index-") for part in parts.parts)
            or any(
                part.casefold() == ".agents"
                and (index != 0 or len(parts.parts) < 3 or parts.parts[1].casefold() != "skills")
                for index, part in enumerate(parts.parts)
            )
            or any(identity == prefix or identity.startswith(prefix + "/") for prefix in NONPRODUCT_PREFIXES)
            or identity in {"groundtruth.db", "groundtruth.db-wal", "groundtruth.db-shm"}
        ):
            refused.append({"path": path, "reason": "not_work_product"})
        else:
            product.append(path)
    return {"status": "fail" if refused else "pass", "refused": refused, "product": product, "removals": removals}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--staged", action="store_true", required=True)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    try:
        result = inspect_staged(Path.cwd())
    except IndexCheckError as error:
        result = {"status": "fail", "error": str(error)}
    if args.json:
        print(json.dumps(result, ensure_ascii=True))
    elif result["status"] == "pass":
        print("PASS staged work product: no ephemeral, generated or runtime postimages")
    else:
        print("FAIL staged work product: " + json.dumps(result, ensure_ascii=True), file=sys.stderr)
    return 0 if result["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
