"""Generate the read-only inventory of the 2026-05-06 codex-backlog-cleanup window.

Reads the project's groundtruth.db work_items table for rows attributed to
``changed_by='codex-backlog-cleanup'`` and emits a markdown table to
``independent-progress-assessments/CODEX-INSIGHT-DROPBOX/CODEX-BACKLOG-CLEANUP-2026-05-06-INVENTORY.md``.

Per ``bridge/gtkb-codex-backlog-cleanup-retroactive-review-003.md`` (GO at -004):
- read-only against the database (no INSERT/UPDATE/DELETE);
- columns: WI id, title, pre-state (resolution_status + stage from the
  immediately prior version), post-state (current version), change_reason,
  changed_at;
- 119 rows expected;
- in-root output per ADR-ISOLATION-APPLICATION-PLACEMENT-001.

This script does not call the KnowledgeDB Python API because the operation is
strictly read-only and the canonical query needs prior-version joins that the
high-level API does not surface; raw sqlite3 read access is appropriate.

(c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB_PATH = PROJECT_ROOT / "groundtruth.db"
DEFAULT_OUTPUT_PATH = (
    PROJECT_ROOT
    / "independent-progress-assessments"
    / "CODEX-INSIGHT-DROPBOX"
    / "CODEX-BACKLOG-CLEANUP-2026-05-06-INVENTORY.md"
)
CHANGED_BY = "codex-backlog-cleanup"
WINDOW_START = "2026-05-06T18:06:00Z"
WINDOW_END = "2026-05-06T18:10:00Z"


def fetch_inventory_rows(db_path: Path) -> list[dict]:
    """Return the inventory rows joined with their immediately prior version state."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute(
            """
            SELECT
                cur.id AS wi_id,
                cur.version AS post_version,
                cur.title AS title,
                cur.resolution_status AS post_resolution_status,
                cur.stage AS post_stage,
                cur.change_reason AS change_reason,
                cur.changed_at AS changed_at,
                prev.resolution_status AS pre_resolution_status,
                prev.stage AS pre_stage,
                prev.version AS pre_version
            FROM work_items AS cur
            LEFT JOIN work_items AS prev
                ON prev.id = cur.id AND prev.version = cur.version - 1
            WHERE cur.changed_by = ?
              AND cur.changed_at >= ?
              AND cur.changed_at <  ?
            ORDER BY cur.changed_at ASC, cur.id ASC
            """,
            (CHANGED_BY, WINDOW_START, WINDOW_END),
        )
        return [dict(row) for row in cur.fetchall()]
    finally:
        conn.close()


def cross_check_window(db_path: Path) -> int:
    """Return distinct WI count via the changed_at window for cross-check."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT COUNT(DISTINCT id) FROM work_items
            WHERE changed_at >= ? AND changed_at < ?
              AND changed_by = ?
            """,
            (WINDOW_START, WINDOW_END, CHANGED_BY),
        )
        return cur.fetchone()[0]
    finally:
        conn.close()


def render_markdown(rows: list[dict], cross_check_count: int) -> str:
    """Render inventory rows as a governance-ready markdown report."""
    lines: list[str] = [
        "# Codex Backlog Cleanup — 2026-05-06 Inventory",
        "",
        "Generated by: `scripts/generate_codex_backlog_cleanup_inventory.py`",
        f"Source attribution: `changed_by = '{CHANGED_BY}'`",
        f"Window: `{WINDOW_START}` <= `changed_at` < `{WINDOW_END}`",
        f"Row count: {len(rows)}",
        f"Cross-check distinct WI count via window+changed_by: {cross_check_count}",
        "",
        "Bridge thread: `bridge/gtkb-codex-backlog-cleanup-retroactive-review` "
        "(GO at -004; this artifact is the Phase-1 inventory deliverable).",
        "",
        "Read-only inventory. No KB mutation occurred during generation.",
        "",
        "## Inventory Table",
        "",
        "| # | WI ID | Title | Pre-state (resolution_status / stage) | Post-state (resolution_status / stage) | change_reason | changed_at |",
        "|---|---|---|---|---|---|---|",
    ]

    for index, row in enumerate(rows, start=1):
        if row["pre_version"] is None:
            pre_state = "(no prior version)"
        else:
            pre_state = f"{row['pre_resolution_status']} / {row['pre_stage']}"
        post_state = f"{row['post_resolution_status']} / {row['post_stage']}"
        title = (row["title"] or "").replace("|", "\\|")
        change_reason = (row["change_reason"] or "").replace("|", "\\|")
        changed_at = row["changed_at"] or ""
        lines.append(
            f"| {index} | `{row['wi_id']}` | {title} | {pre_state} | {post_state} | {change_reason} | `{changed_at}` |"
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "*(c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.*",
        ]
    )
    return "\n".join(lines) + "\n"


def write_output(content: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args(argv)

    if not args.db.exists():
        print(f"ERROR: db not found: {args.db}", file=sys.stderr)
        return 2

    rows = fetch_inventory_rows(args.db)
    cross_check = cross_check_window(args.db)
    if cross_check != len(rows):
        print(
            f"WARN: row count {len(rows)} differs from window cross-check "
            f"distinct count {cross_check}; investigate attribution drift.",
            file=sys.stderr,
        )

    content = render_markdown(rows, cross_check)
    write_output(content, args.out)
    print(f"Wrote {len(rows)} inventory rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
