#!/usr/bin/env python3
"""Generate Antigravity project skill adapters from canonical GT-KB skills.

WI-3347 (Antigravity Onboarding sub-project of PROJECT-ANTIGRAVITY-INTEGRATION).
Builds ``.agent/skills/<name>/SKILL.md`` adapters for the capabilities whose
harness-capability-registry ``required_for_roles`` includes ``loyal-opposition``
(DELIB-2079 Q8 role-scoped parity). Antigravity is onboarded solely in the
loyal-opposition role, so it receives only the LO-scoped subset of skills, not
the full set the Codex harness carries.

This generator reuses the harness-agnostic helpers of
``generate_codex_skill_adapters.py``; that script is not modified. The
Antigravity-specific behaviour is: the loyal-opposition role filter, the
``.agent/skills/`` target directory, the ``GTKB-ANTIGRAVITY-SKILL-ADAPTER``
marker, registry blocks that are inserted (not just rewritten), and BOM-aware
frontmatter placement -- Antigravity parses each adapter's YAML frontmatter for
the mandatory ``description`` trigger, so the generated marker block must follow
the frontmatter and the file must not begin with a UTF-8 BOM.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

# Make the sibling Codex generator importable regardless of how this module is
# loaded (direct invocation, or importlib.spec_from_file_location in tests).
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

import generate_codex_skill_adapters as codex_gen  # noqa: E402

PROJECT_ROOT = _SCRIPT_DIR.parent
REGISTRY_RELATIVE_PATH = Path("config") / "agent-control" / "harness-capability-registry.toml"
ANTIGRAVITY_SKILLS_RELATIVE_PATH = Path(".agent") / "skills"
GENERATED_MARKER = "<!-- GTKB-ANTIGRAVITY-SKILL-ADAPTER"
GENERATED_END_MARKER = "GTKB-ANTIGRAVITY-SKILL-ADAPTER -->"
MANIFEST_NAME = "MANIFEST.json"
GENERATOR_NAME = "scripts/generate_antigravity_skill_adapters.py"
ANTIGRAVITY_ROLE = "loyal-opposition"
REGISTRY_HARNESS_TABLE = "[capabilities.antigravity]"
BOM = chr(0xFEFF)  # U+FEFF byte-order mark

# Harness-agnostic helpers reused from the Codex generator. These operate on
# canonical sources (which carry no generated block) and on plain text, so they
# are marker-independent for this generator's use.
_sha256_text = codex_gen._sha256_text
_strip_generated_block = codex_gen._strip_generated_block
_now_iso = codex_gen._now_iso
_relative_path = codex_gen._relative_path
_existing_generated_at = codex_gen._existing_generated_at
_write_if_changed = codex_gen._write_if_changed


@dataclass(frozen=True)
class SkillAdapter:
    capability_id: str
    canonical_name: str
    source_relative_path: str
    adapter_relative_path: str
    source_sha256: str


def _lo_skill_capabilities(registry: dict) -> list[dict]:
    """Skill capabilities whose required_for_roles includes loyal-opposition."""

    raw = registry.get("capabilities")
    if not isinstance(raw, list):
        return []
    selected: list[dict] = []
    for capability in raw:
        if not isinstance(capability, dict):
            continue
        if capability.get("kind") != "skill":
            continue
        if not str(capability.get("canonical_source") or "").endswith("/SKILL.md"):
            continue
        roles = capability.get("required_for_roles")
        if not isinstance(roles, list):
            continue
        if ANTIGRAVITY_ROLE in [str(role).strip().lower() for role in roles]:
            selected.append(capability)
    return selected


def _adapter_relative_path(source_relative_path: str) -> str:
    skill_directory = Path(source_relative_path).parent.name
    return (ANTIGRAVITY_SKILLS_RELATIVE_PATH / skill_directory / "SKILL.md").as_posix()


def _generated_block(adapter: SkillAdapter, generated_at: str) -> str:
    return "\n".join(
        [
            GENERATED_MARKER,
            "Generated: true",
            f"Generated by: {GENERATOR_NAME}",
            f"Canonical source: {adapter.source_relative_path}",
            f"Canonical source sha256: {adapter.source_sha256}",
            f"Generated at: {generated_at}",
            "Do not edit this adapter directly. Edit the canonical source and regenerate.",
            GENERATED_END_MARKER,
            "",
        ]
    )


def render_adapter(source_text: str, adapter: SkillAdapter, *, generated_at: str) -> str:
    """Render an Antigravity adapter: canonical body + marker block.

    The marker block is placed after the YAML frontmatter so Antigravity can
    parse the mandatory ``description`` field. A leading UTF-8 BOM on the
    canonical source is stripped so the frontmatter is the first content.
    """

    body = _strip_generated_block(source_text)
    if body.startswith(BOM):
        body = body[len(BOM):]
    body = body.rstrip() + "\n"
    block = _generated_block(adapter, generated_at)
    lines = body.splitlines(keepends=True)
    if lines and lines[0].strip() == "---":
        for index, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                return "".join(lines[: index + 1]) + block + "".join(lines[index + 1 :])
    return block + body


def build_adapters(project_root: Path) -> list[SkillAdapter]:
    registry_path = project_root / REGISTRY_RELATIVE_PATH
    registry = tomllib.loads(registry_path.read_text(encoding="utf-8"))
    adapters: list[SkillAdapter] = []
    for capability in _lo_skill_capabilities(registry):
        source_relative_path = str(capability.get("canonical_source") or "")
        source_text = (project_root / source_relative_path).read_text(encoding="utf-8")
        # source_sha256 is the canonical-body hash, computed identically to the
        # Codex generator so both harnesses share one hash contract.
        source_sha256 = _sha256_text(_strip_generated_block(source_text).rstrip() + "\n")
        adapters.append(
            SkillAdapter(
                capability_id=str(capability.get("id") or ""),
                canonical_name=str(capability.get("canonical_name") or ""),
                source_relative_path=source_relative_path,
                adapter_relative_path=_adapter_relative_path(source_relative_path),
                source_sha256=source_sha256,
            )
        )
    return adapters


def _manifest_content(adapters: list[SkillAdapter]) -> str:
    payload = {
        "schema_version": 1,
        "generated_by": GENERATOR_NAME,
        "harness": "antigravity",
        "adapters": [adapter.__dict__ for adapter in adapters],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _antigravity_subsection_lines(adapter: SkillAdapter) -> list[str]:
    return [
        REGISTRY_HARNESS_TABLE,
        f'surface = "{adapter.adapter_relative_path}"',
        'status = "adapter"',
        f'adapter_source = "{adapter.source_relative_path}"',
        f'source_sha256 = "{adapter.source_sha256}"',
    ]


def _emit_antigravity_block(output: list[str], adapter: SkillAdapter) -> None:
    """Append a [capabilities.antigravity] block to ``output``, preceded by
    exactly one blank line to match the registry's blank-line-before-subtable
    style. Any trailing blank lines already in ``output`` are collapsed first."""

    while output and output[-1].strip() == "":
        output.pop()
    output.append("")
    output.extend(_antigravity_subsection_lines(adapter))


def _apply_antigravity_registry(text: str, adapters: list[SkillAdapter]) -> str:
    """Insert or rewrite a [capabilities.antigravity] block per LO-scoped capability.

    The block is placed last in its [[capabilities]] entry (after the
    [capabilities.codex] block). On a re-run an existing block is replaced.
    Capabilities not in the LO-scoped adapter set are left untouched.
    """

    adapters_by_source = {adapter.source_relative_path: adapter for adapter in adapters}
    lines = text.splitlines()
    output: list[str] = []
    current_source: str | None = None
    pending_adapter: SkillAdapter | None = None
    skipping_old_block = False

    for line in lines:
        stripped = line.strip()

        if skipping_old_block:
            if stripped.startswith("["):
                skipping_old_block = False
            else:
                continue

        if stripped.startswith("[[capabilities]]"):
            if pending_adapter is not None:
                _emit_antigravity_block(output, pending_adapter)
                pending_adapter = None
            current_source = None
            output.append(line)
            continue

        if stripped.startswith("canonical_source"):
            current_source = stripped.split("=", 1)[1].strip().strip('"')
            pending_adapter = adapters_by_source.get(current_source)
            output.append(line)
            continue

        if stripped == REGISTRY_HARNESS_TABLE:
            adapter = adapters_by_source.get(current_source or "")
            if adapter is not None:
                _emit_antigravity_block(output, adapter)
                pending_adapter = None
                skipping_old_block = True
                continue
            output.append(line)
            continue

        output.append(line)

    if pending_adapter is not None:
        _emit_antigravity_block(output, pending_adapter)

    return "\n".join(output).rstrip() + "\n"


def update_registry(project_root: Path, adapters: list[SkillAdapter], *, check: bool = False) -> bool:
    registry_path = project_root / REGISTRY_RELATIVE_PATH
    current = registry_path.read_text(encoding="utf-8")
    updated = _apply_antigravity_registry(current, adapters)
    if current == updated:
        return False
    if not check:
        registry_path.write_text(updated, encoding="utf-8")
    return True


def _remove_orphan_adapters(project_root: Path, adapters: list[SkillAdapter], *, check: bool) -> list[str]:
    skills_root = project_root / ANTIGRAVITY_SKILLS_RELATIVE_PATH
    if not skills_root.is_dir():
        return []
    expected = {project_root / adapter.adapter_relative_path for adapter in adapters}
    expected.add(skills_root / MANIFEST_NAME)
    orphans: list[str] = []
    for skill_file in sorted(skills_root.glob("*/SKILL.md")):
        if skill_file in expected:
            continue
        if GENERATED_MARKER not in skill_file.read_text(encoding="utf-8"):
            continue
        orphans.append(_relative_path(project_root, skill_file))
        if not check:
            skill_file.unlink()
            try:
                skill_file.parent.rmdir()
            except OSError:
                pass
    return orphans


def generate(project_root: Path, *, check: bool = False) -> tuple[list[str], list[str]]:
    project_root = project_root.resolve()
    adapters = build_adapters(project_root)
    changed: list[str] = []
    for adapter in adapters:
        source_text = (project_root / adapter.source_relative_path).read_text(encoding="utf-8")
        adapter_path = project_root / adapter.adapter_relative_path
        existing_text = adapter_path.read_text(encoding="utf-8") if adapter_path.is_file() else None
        generated_at = _existing_generated_at(existing_text) or _now_iso()
        rendered = render_adapter(source_text, adapter, generated_at=generated_at)
        if _write_if_changed(adapter_path, rendered, check=check):
            changed.append(adapter.adapter_relative_path)

    manifest_path = project_root / ANTIGRAVITY_SKILLS_RELATIVE_PATH / MANIFEST_NAME
    if _write_if_changed(manifest_path, _manifest_content(adapters), check=check):
        changed.append(_relative_path(project_root, manifest_path))
    changed.extend(_remove_orphan_adapters(project_root, adapters, check=check))
    return changed, [adapter.adapter_relative_path for adapter in adapters]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--check", action="store_true", help="Report drift without writing files.")
    parser.add_argument(
        "--update-registry",
        action="store_true",
        help="Insert or update [capabilities.antigravity] capability-registry blocks.",
    )
    args = parser.parse_args(argv)

    changed, adapter_paths = generate(args.project_root, check=args.check)
    if args.update_registry:
        adapters = build_adapters(args.project_root.resolve())
        if update_registry(args.project_root.resolve(), adapters, check=args.check):
            changed.append(REGISTRY_RELATIVE_PATH.as_posix())

    if changed:
        action = "would update" if args.check else "updated"
        print(f"Antigravity skill adapters: {action} {len(changed)} file(s)")
        for path in changed:
            print(f"- {path}")
        return 1 if args.check else 0

    print(f"Antigravity skill adapters: PASS ({len(adapter_paths)} adapters current)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
