#!/usr/bin/env python3
"""Generate Codex project skill adapters from canonical GT-KB skills."""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_RELATIVE_PATH = Path("config") / "agent-control" / "harness-capability-registry.toml"
CODEX_SKILLS_RELATIVE_PATH = Path(".codex") / "skills"
GENERATED_MARKER = "<!-- GTKB-CODEX-SKILL-ADAPTER"
GENERATED_END_MARKER = "GTKB-CODEX-SKILL-ADAPTER -->"
MANIFEST_NAME = "MANIFEST.json"


@dataclass(frozen=True)
class SkillAdapter:
    capability_id: str
    canonical_name: str
    source_relative_path: str
    adapter_relative_path: str
    source_sha256: str


def _now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _relative_path(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _load_registry(project_root: Path) -> dict[str, Any]:
    registry_path = project_root / REGISTRY_RELATIVE_PATH
    return tomllib.loads(registry_path.read_text(encoding="utf-8"))


def _skill_capabilities(registry: dict[str, Any]) -> list[dict[str, Any]]:
    raw_capabilities = registry.get("capabilities")
    if not isinstance(raw_capabilities, list):
        return []
    return [
        capability
        for capability in raw_capabilities
        if isinstance(capability, dict)
        and capability.get("kind") == "skill"
        and str(capability.get("canonical_source") or "").endswith("/SKILL.md")
    ]


def _adapter_relative_path(source_relative_path: str) -> str:
    source_path = Path(source_relative_path)
    skill_directory = source_path.parent.name
    return (CODEX_SKILLS_RELATIVE_PATH / skill_directory / "SKILL.md").as_posix()


def _generated_block(adapter: SkillAdapter, generated_at: str) -> str:
    return "\n".join(
        [
            GENERATED_MARKER,
            "Generated: true",
            "Generated by: scripts/generate_codex_skill_adapters.py",
            f"Canonical source: {adapter.source_relative_path}",
            f"Canonical source sha256: {adapter.source_sha256}",
            f"Generated at: {generated_at}",
            "Do not edit this adapter directly. Edit the canonical source and regenerate.",
            GENERATED_END_MARKER,
            "",
        ]
    )


def _strip_generated_block(text: str) -> str:
    start = text.find(GENERATED_MARKER)
    if start == -1:
        return text
    end = text.find(GENERATED_END_MARKER, start)
    if end == -1:
        return text
    return text[:start] + text[end + len(GENERATED_END_MARKER) :].lstrip("\r\n")


def _existing_generated_at(existing_text: str | None) -> str | None:
    if not existing_text:
        return None
    for line in existing_text.splitlines():
        if line.startswith("Generated at:"):
            return line.split(":", 1)[1].strip() or None
    return None


def render_adapter(source_text: str, adapter: SkillAdapter, *, generated_at: str) -> str:
    source_text = _strip_generated_block(source_text).rstrip() + "\n"
    block = _generated_block(adapter, generated_at)
    lines = source_text.splitlines(keepends=True)
    if lines and lines[0].strip() == "---":
        for index, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                return "".join(lines[: index + 1]) + block + "".join(lines[index + 1 :])
    return block + source_text


def build_adapters(project_root: Path) -> list[SkillAdapter]:
    registry = _load_registry(project_root)
    adapters: list[SkillAdapter] = []
    for capability in _skill_capabilities(registry):
        source_relative_path = str(capability.get("canonical_source") or "")
        source_path = project_root / source_relative_path
        source_text = source_path.read_text(encoding="utf-8")
        source_sha256 = _sha256_text(_strip_generated_block(source_text).rstrip() + "\n")
        adapters.append(
            SkillAdapter(
                capability_id=str(capability.get("id") or ""),
                canonical_name=str(capability.get("canonical_name") or ""),
                source_relative_path=source_relative_path,
                adapter_relative_path=_adapter_relative_path(source_relative_path),
                source_sha256=source_sha256,
            )
        )
    return adapters


def _write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    if existing == content:
        return False
    if check:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _manifest_content(adapters: list[SkillAdapter]) -> str:
    payload = {
        "schema_version": 1,
        "generated_by": "scripts/generate_codex_skill_adapters.py",
        "adapters": [adapter.__dict__ for adapter in adapters],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _registry_adapter_block(adapter: SkillAdapter) -> list[str]:
    return [
        f'surface = "{adapter.adapter_relative_path}"',
        'status = "adapter"',
        f'adapter_source = "{adapter.source_relative_path}"',
        f'source_sha256 = "{adapter.source_sha256}"',
    ]


def _rewrite_registry_text(text: str, adapters: list[SkillAdapter]) -> str:
    adapters_by_source = {adapter.source_relative_path: adapter for adapter in adapters}
    lines = text.splitlines()
    output: list[str] = []
    current_source: str | None = None
    skipping_codex_block = False
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        if skipping_codex_block and stripped.startswith("["):
            skipping_codex_block = False
            continue
        if skipping_codex_block:
            index += 1
            continue

        if stripped.startswith("[[capabilities]]"):
            current_source = None
        elif stripped.startswith("canonical_source"):
            current_source = stripped.split("=", 1)[1].strip().strip('"')

        if stripped == "[capabilities.codex]" and current_source in adapters_by_source:
            output.append(line)
            output.extend(_registry_adapter_block(adapters_by_source[current_source]))
            skipping_codex_block = True
            index += 1
            continue

        output.append(line)
        index += 1

    return "\n".join(output).rstrip() + "\n"


def update_registry(project_root: Path, adapters: list[SkillAdapter], *, check: bool = False) -> bool:
    registry_path = project_root / REGISTRY_RELATIVE_PATH
    current = registry_path.read_text(encoding="utf-8")
    updated = _rewrite_registry_text(current, adapters)
    if current == updated:
        return False
    if not check:
        registry_path.write_text(updated, encoding="utf-8")
    return True


def _remove_orphan_adapters(project_root: Path, adapters: list[SkillAdapter], *, check: bool) -> list[str]:
    skills_root = project_root / CODEX_SKILLS_RELATIVE_PATH
    if not skills_root.is_dir():
        return []
    expected = {project_root / adapter.adapter_relative_path for adapter in adapters}
    expected.add(skills_root / MANIFEST_NAME)
    orphans: list[str] = []
    for skill_file in sorted(skills_root.glob("*/SKILL.md")):
        if skill_file in expected:
            continue
        text = skill_file.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        orphans.append(_relative_path(project_root, skill_file))
        if not check:
            skill_file.unlink()
            try:
                skill_file.parent.rmdir()
            except OSError:
                pass
    return orphans


def generate(project_root: Path, *, check: bool = False) -> tuple[list[str], list[str]]:
    project_root = project_root.resolve()
    adapters = build_adapters(project_root)
    changed: list[str] = []
    for adapter in adapters:
        source_text = (project_root / adapter.source_relative_path).read_text(encoding="utf-8")
        adapter_path = project_root / adapter.adapter_relative_path
        existing_text = adapter_path.read_text(encoding="utf-8") if adapter_path.is_file() else None
        generated_at = _existing_generated_at(existing_text) or _now_iso()
        rendered = render_adapter(source_text, adapter, generated_at=generated_at)
        if _write_if_changed(adapter_path, rendered, check=check):
            changed.append(adapter.adapter_relative_path)

    manifest_path = project_root / CODEX_SKILLS_RELATIVE_PATH / MANIFEST_NAME
    if _write_if_changed(manifest_path, _manifest_content(adapters), check=check):
        changed.append(_relative_path(project_root, manifest_path))
    orphans = _remove_orphan_adapters(project_root, adapters, check=check)
    changed.extend(orphans)
    return changed, [adapter.adapter_relative_path for adapter in adapters]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--check", action="store_true", help="Report drift without writing files.")
    parser.add_argument(
        "--update-registry",
        action="store_true",
        help="Point Codex skill capability entries at generated adapters.",
    )
    args = parser.parse_args(argv)

    changed, adapter_paths = generate(args.project_root, check=args.check)
    adapters = build_adapters(args.project_root.resolve())
    if args.update_registry and update_registry(args.project_root.resolve(), adapters, check=args.check):
        changed.append(REGISTRY_RELATIVE_PATH.as_posix())
    if changed:
        action = "would update" if args.check else "updated"
        print(f"Codex skill adapters: {action} {len(changed)} file(s)")
        for path in changed:
            print(f"- {path}")
        return 1 if args.check else 0

    print(f"Codex skill adapters: PASS ({len(adapter_paths)} adapters current)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
