# sync-admin-env.ps1 — Distribute VITE_* variables to admin SPA directories.
#
# Reads the root .env.local file and writes a minimal .env.local into each
# admin SPA directory (shopify, standalone, provider) so that Vite dev server
# and build processes pick up the correct API URLs and keys.
#
# Usage:
#   powershell -File scripts/sync-admin-env.ps1          # from repo root
#   powershell -File scripts/sync-admin-env.ps1 -DryRun  # preview without writing
#
# This script is idempotent — safe to run repeatedly.
#
# © 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.

param(
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

# --- Configuration ---------------------------------------------------------
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Definition)
$SourceEnv = Join-Path $RepoRoot '.env.local'

# Variables to distribute to admin SPAs
$ViteVars = @(
    'VITE_API_URL',
    'VITE_SHOPIFY_API_KEY'
)

# Target SPA directories
$AdminDir = Join-Path $RepoRoot 'admin'
$AdminDirs = @(
    (Join-Path $AdminDir 'shopify'),
    (Join-Path $AdminDir 'standalone'),
    (Join-Path $AdminDir 'provider')
)

# --- Read source -----------------------------------------------------------
if (-not (Test-Path $SourceEnv)) {
    Write-Error "Source file not found: $SourceEnv"
    exit 1
}

Write-Host "Reading: $SourceEnv" -ForegroundColor Cyan

$Vars = @{}
Get-Content $SourceEnv | ForEach-Object {
    $line = $_.Trim()
    # Skip comments and blank lines
    if ($line -eq '' -or $line.StartsWith('#')) { return }
    # Parse KEY=VALUE
    $eq = $line.IndexOf('=')
    if ($eq -gt 0) {
        $key = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim()
        if ($ViteVars -contains $key) {
            $Vars[$key] = $value
        }
    }
}

if ($Vars.Count -eq 0) {
    Write-Warning "No VITE_* variables found in $SourceEnv. Nothing to sync."
    exit 0
}

Write-Host "Found $($Vars.Count) variable(s) to distribute:" -ForegroundColor Cyan
foreach ($kv in $Vars.GetEnumerator()) {
    # Mask values for safety — show first 12 chars only
    $masked = if ($kv.Value.Length -gt 12) { $kv.Value.Substring(0, 12) + '...' } else { $kv.Value }
    Write-Host "  $($kv.Key) = $masked" -ForegroundColor Gray
}

# --- Write to each SPA directory -------------------------------------------
$header = @(
    '# Auto-generated by scripts/sync-admin-env.ps1',
    '# Source: root .env.local',
    "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    '# DO NOT EDIT -- re-run sync-admin-env.ps1 to update.',
    '#',
    '# (c) 2026 Remaker Digital, a DBA of VanDusen & Palmeter, LLC. All rights reserved.',
    ''
)

foreach ($dir in $AdminDirs) {
    $target = Join-Path $dir '.env.local'
    $dirName = Split-Path $dir -Leaf

    if (-not (Test-Path $dir)) {
        Write-Warning "Directory not found, skipping: $dir"
        continue
    }

    $lines = $header.Clone()
    foreach ($kv in $Vars.GetEnumerator()) {
        $lines += "$($kv.Key)=$($kv.Value)"
    }
    $content = ($lines -join "`n") + "`n"

    if ($DryRun) {
        Write-Host "[DRY RUN] Would write: $target" -ForegroundColor Yellow
        Write-Host ($lines | Where-Object { -not $_.StartsWith('#') -and $_ -ne '' } | ForEach-Object { "  $_" }) -ForegroundColor Gray
    }
    else {
        Set-Content -Path $target -Value $content -NoNewline -Encoding UTF8
        Write-Host "[OK] $dirName/.env.local written ($($Vars.Count) vars)" -ForegroundColor Green
    }
}

# --- Summary ---------------------------------------------------------------
if ($DryRun) {
    Write-Host "`nDry run complete. No files were written." -ForegroundColor Yellow
}
else {
    Write-Host "`nSync complete. $($AdminDirs.Count) admin .env.local files updated." -ForegroundColor Green
}
