param(
    [string]$EnvFile = ".env.local"
)

$ErrorActionPreference = "Stop"

function Resolve-AppRoot {
    if ($env:AGENT_RED_APP_ROOT_OVERRIDE) {
        return (Resolve-Path -LiteralPath $env:AGENT_RED_APP_ROOT_OVERRIDE).Path
    }
    $scriptDir = Split-Path -Parent $PSCommandPath
    return (Resolve-Path -LiteralPath (Join-Path $scriptDir "..")).Path
}

function Read-EnvFile {
    param([string]$Path)
    $result = [ordered]@{}
    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) {
            continue
        }
        $parts = $trimmed -split "=", 2
        if ($parts.Count -eq 2) {
            $result[$parts[0].Trim()] = $parts[1].Trim().Trim('"').Trim("'")
        }
    }
    return $result
}

$appRoot = Resolve-AppRoot
$sourcePath = Join-Path $appRoot $EnvFile
if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Agent Red environment file not found: $EnvFile"
}

$values = Read-EnvFile -Path $sourcePath
$targets = @(
    "admin/standalone/.env.local",
    "admin/provider/.env.local",
    "admin/shopify/.env.local"
)

foreach ($relative in $targets) {
    $targetPath = Join-Path $appRoot $relative
    $targetDir = Split-Path -Parent $targetPath
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    $lines = @("# Generated by applications/Agent_Red/scripts/sync-admin-env.ps1")
    foreach ($key in $values.Keys) {
        $lines += "$key=$($values[$key])"
    }
    Set-Content -LiteralPath $targetPath -Value $lines -Encoding utf8
}

Write-Host "Synchronized Agent Red admin environment files."
